import type { TrackRecordPhoto, TrackRecordActivity, TrackRecordYear } from "./track-record-types";

export const trackRecordData: TrackRecordYear[] = [
  {
    year: 2010,
    activities: [
      {
        id: "reboisasi-gunung-klabat",
        title: "Reboisasi Gunung Klabat",
        titleKey: "trackRecordData.activity.0.title",
        narrativeKey: "trackRecordData.activity.0.narrative",
        location: "Gunung Klabat",
        role: "Mitra Pelaksana",
        era: "awal",
        categories: ["lingkungan"],
        narrative:
          "Awal mula kepedulian Baciraro terhadap lingkungan. Program reboisasi di kawasan Gunung Klabat bersama relawan Aqua, menanam pohon untuk menjaga kelestarian hutan dan sumber daya air di Sulawesi Utara.",
        photos: [
          { src: "/2010/kegiatan tanam pohon dengan relawan aqua di batas hutan gunung klabat.webp", alt: "Kegiatan tanam pohon dengan relawan Aqua di batas hutan Gunung Klabat" },
          { src: "/2010/tanam pohon di gunung klabat.webp", alt: "Tanam pohon di Gunung Klabat" },
          { src: "/2010/tanam pohon di gunung klabat 2.webp", alt: "Tanam pohon di Gunung Klabat" },
        ],
      },
    ],
  },
  {
    year: 2011,
    activities: [
      {
        id: "salvos-go-green",
        title: "Salvos Go Green",
        titleKey: "trackRecordData.activity.1.title",
        narrativeKey: "trackRecordData.activity.1.narrative",
        location: "Sulawesi Utara",
        role: "Pendukung",
        era: "awal",
        categories: ["lingkungan", "sosial"],
        narrative:
          "Program Salvos Go Green, aksi peduli lingkungan oleh Gereja Bala Keselamatan yang melibatkan penanaman pohon dan edukasi lingkungan di Sulawesi Utara. Aksi tanam pohon oleh Pemuda Gereja Bala Keselamatan se-Indonesia berfokus pada penghijauan dan kepedulian lingkungan.",
        photos: [
          { src: "/2011/salvos go green.png", alt: "Salvos Go Green" },
          { src: "/2011/kegiatan tanam pohon Salvos Go Green Pemuda Gereja Bala Keselamatan se Indonesia.jpg", alt: "Tanam pohon Salvos Go Green" },
        ],
      },
    ],
  },
  {
    year: 2012,
    activities: [
      {
        id: "bank-sampah-brits-bunaken",
        title: "Pengelolaan Sampah Berbasis Komunitas Pulau Bunaken",
        titleKey: "trackRecordData.activity.2.title",
        narrativeKey: "trackRecordData.activity.2.narrative",
        location: "Pulau Bunaken",
        role: "Pendamping Komunitas",
        era: "awal",
        categories: ["lingkungan", "sosial", "ekonomi"],
        capabilities: ["pendampingan-komunitas", "pengelolaan-sampah-wisata"],
        featured: true,
        narrative:
          "Pendampingan kelompok pengelola sampah BRITS di Pulau Bunaken. Bekerja sama dengan Badan Lingkungan Hidup Provinsi Sulawesi Utara. Implementasi sistem Bank Sampah berbasis masyarakat. Menghasilkan penghargaan MDGs 2012 untuk pengelolaan sampah berbasis prakarsa komunitas lokal.",
        highlights: [
          "Pendampingan kelompok pengelola sampah BRITS di Pulau Bunaken",
          "Kerja sama dengan Badan Lingkungan Hidup Provinsi Sulawesi Utara",
          "Implementasi sistem Bank Sampah berbasis masyarakat",
          "Penghargaan MDGs 2012 untuk pengelolaan sampah berbasis prakarsa komunitas lokal",
        ],
        photos: [
          { src: "/2012/Manado-Bunaken (29).jpg", alt: "Manado-Bunaken" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (1).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (2).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (3).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (4).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (5).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (6).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (7).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (8).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (9).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (10).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (11).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (12).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (13).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (14).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (15).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
          { src: "/2012/Pengolahan Bank Sampah Brits di Pulau Bunaken 2012 (16).jpg", alt: "Pengolahan Bank Sampah Brits di Pulau Bunaken 2012" },
        ],
      },
    ],
  },
  {
    year: 2013,
    activities: [
      {
        id: "klabat-lestari-aqua",
        title: "Program Klabat Lestari bersama Aqua",
        titleKey: "trackRecordData.activity.3.title",
        narrativeKey: "trackRecordData.activity.3.narrative",
        location: "Gunung Klabat",
        role: "Mitra Pelaksana",
        era: "tumbuh",
        categories: ["lingkungan"],
        capabilities: ["pendampingan-komunitas"],
        narrative:
          "Program konservasi Gunung Klabat bersama Aqua. Melibatkan kelompok binaan dalam kegiatan pelestarian lingkungan, penghijauan, dan pengelolaan sampah di kawasan Gunung Klabat.",
        photos: [
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua.jpg", alt: "Kegiatan dengan kelompok binaan dari PT Aqua" },
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua launching program klabat lestari 2.png", alt: "Launching program Klabat Lestari" },
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua launching program klabat lestari 3.png", alt: "Launching program Klabat Lestari" },
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua launching program klabat lestari 4.png", alt: "Launching program Klabat Lestari" },
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua launching program klabat lestari launching program klabat lestari 5.png", alt: "Launching program Klabat Lestari" },
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua launching program klabat lestari launching program klabat lestari 6.jpg", alt: "Kegiatan Klabat Lestari" },
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua launching program klabat lestari launching program klabat lestari 7.jpg", alt: "Kegiatan Klabat Lestari" },
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua launching program klabat lestari launching program klabat lestari 8.jpg", alt: "Kegiatan Klabat Lestari" },
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua launching program klabat lestari launching program klabat lestari 9.jpg", alt: "Kegiatan Klabat Lestari" },
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua launching program klabat lestari launching program klabat lestari 10.jpg", alt: "Kegiatan Klabat Lestari" },
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua launching program klabat lestari launching program klabat lestari 11.jpg", alt: "Kegiatan Klabat Lestari" },
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua launching program klabat lestari launching program klabat lestari 12.jpg", alt: "Kegiatan Klabat Lestari" },
          { src: "/2013/kegiatan dengan kelompok binaan dari pt aqua launching program klabat lestari launching program klabat lestari 13.jpg", alt: "Kegiatan Klabat Lestari" },
        ],
      },
      {
        id: "biogas-kencana-online",
        title: "Studi Biogas & Teknologi Kencana Online",
        titleKey: "trackRecordData.activity.4.title",
        narrativeKey: "trackRecordData.activity.4.narrative",
        location: "Bandung",
        role: "Peserta Studi",
        era: "tumbuh",
        categories: ["teknologi", "lingkungan"],
        capabilities: ["biogas-energi-terbarukan"],
        narrative:
          "Kunjungan tim koperasi Minahasa ke PT Kencana Online di Bandung untuk mempelajari teknologi biogas, komposter, dan energi terbarukan. Mempelajari sistem biodigester, genset biogas, kompor biogas, dan pemurnian biogas untuk pengelolaan energi berkelanjutan.",
        photos: [
          { src: "/2013/kunjungan tim koperasi minahasa ke pt kencana online.png", alt: "Kunjungan tim koperasi Minahasa ke PT Kencana Online" },
          { src: "/2013/kunjungan tim koperasi minahasa ke pt kencana online (biodigester).jpg", alt: "Biodigester di Kencana Online" },
          { src: "/2013/kunjungan tim koperasi minahasa ke pt kencana online (biogas).jpg", alt: "Biogas di Kencana Online" },
          { src: "/2013/kunjungan tim koperasi minahasa ke pt kencana online (genset biogas).jpg", alt: "Genset biogas" },
          { src: "/2013/kunjungan tim koperasi minahasa ke pt kencana online (inverter, batre, untuk meyimpan energi listrik dari biogas).jpg", alt: "Inverter dan baterai untuk penyimpanan energi listrik dari biogas" },
          { src: "/2013/kunjungan tim koperasi minahasa ke pt kencana online (kompor biogas).jpg", alt: "Kompor biogas" },
          { src: "/2013/kunjungan tim koperasi minahasa ke pt kencana online (kompor biogas 2).jpg", alt: "Kompor biogas" },
          { src: "/2013/kunjungan tim koperasi minahasa ke pt kencana online (lampu dari biogas).jpg", alt: "Lampu dari biogas" },
          { src: "/2013/kunjungan tim koperasi minahasa ke pt kencana online (penampungan pupuk cair).jpg", alt: "Penampungan pupuk cair" },
          { src: "/2013/kunjungan tim koperasi minahasa ke pt kencana online (refinering).jpg", alt: "Refinering biogas" },
          { src: "/2013/komposter kencana online di bandung.jpg", alt: "Komposter Kencana Online di Bandung" },
          { src: "/2013/komposter kencana online di bandung 2.jpg", alt: "Komposter Kencana Online di Bandung" },
          { src: "/2013/komposter kencana online di bandung 3.jpg", alt: "Komposter Kencana Online di Bandung" },
          { src: "/2013/komposter kencana online di bandung bagian inventer.jpg", alt: "Inventer komposter" },
          { src: "/2013/komposter kencana online di bandung dengan teknologi refineri.jpg", alt: "Komposter dengan teknologi refinery" },
        ],
      },
      {
        id: "tpa-tondano",
        title: "Observasi TPA Tondano",
        titleKey: "trackRecordData.activity.5.title",
        narrativeKey: "trackRecordData.activity.5.narrative",
        location: "Tondano",
        role: "Observer",
        era: "tumbuh",
        categories: ["lingkungan"],
        narrative:
          "Observasi kondisi Tempat Pemrosesan Akhir (TPA) di Tondano untuk memahami sistem pengelolaan sampah dan dampaknya terhadap lingkungan sekitar.",
        photos: [
          { src: "/2013/kondisi TPA di Tondano.jpg", alt: "Kondisi TPA di Tondano" },
          { src: "/2013/kondisi TPA di Tondano 2.jpg", alt: "Kondisi TPA di Tondano" },
        ],
      },
      {
        id: "sungai-manado",
        title: "Dokumentasi Pencemaran Sungai Manado",
        titleKey: "trackRecordData.activity.6.title",
        narrativeKey: "trackRecordData.activity.6.narrative",
        location: "Manado",
        role: "Advokasi",
        era: "tumbuh",
        categories: ["lingkungan"],
        capabilities: ["edukasi-lingkungan"],
        beforeAfter: { before: "/2013/sampah di anak sungai manado.jpg", after: "/2013/sampah di anak sungai manado (after).jpg" },
        featured: true,
        narrative:
          "Dokumentasi kondisi sungai di Manado yang tercemar sampah. Data dan dokumentasi ini menjadi dasar advokasi dan edukasi pengelolaan sampah di Kota Manado.",
        photos: [
          { src: "/2013/sampah di anak sungai manado.jpg", alt: "Sampah di anak sungai Manado" },
          { src: "/2013/sampah di anak sungai manado 2.jpg", alt: "Sampah di anak sungai Manado" },
          { src: "/2013/sampah di anak sungai manado 3.jpg", alt: "Sampah di anak sungai Manado" },
          { src: "/2013/sampah di anak sungai manado 4.jpg", alt: "Sampah di anak sungai Manado" },
          { src: "/2013/sampah di anak sungai manado 5.jpg", alt: "Sampah di anak sungai Manado" },
          { src: "/2013/sampah di anak sungai manado 6.jpg", alt: "Sampah di anak sungai Manado" },
          { src: "/2013/sampah di anak sungai manado 7.jpg", alt: "Sampah di anak sungai Manado" },
          { src: "/2013/sampah di anak sungai manado 8.jpg", alt: "Sampah di anak sungai Manado" },
          { src: "/2013/sampah di anak sungai manado 9.jpg", alt: "Sampah di anak sungai Manado" },
          { src: "/2013/sampah di anak sungai manado 10.jpg", alt: "Sampah di anak sungai Manado" },
          { src: "/2013/sampah di anak sungai manado 11.jpg", alt: "Sampah di anak sungai Manado" },
          { src: "/2013/sampah di anak sungai manado 12.jpg", alt: "Sampah di anak sungai Manado" },
          { src: "/2013/sampah di anak sungai manado (after).jpg", alt: "Setelah pembersihan sungai" },
          { src: "/2013/sampah di anak sungai manado (after) 2.jpg", alt: "Setelah pembersihan sungai" },
          { src: "/2013/tumpukan sampah di manado .jpg", alt: "Tumpukan sampah di Manado" },
          { src: "/2013/tumpukan sampah di manado 2.jpg", alt: "Tumpukan sampah di Manado" },
          { src: "/2013/tumpukan sampah di manado 3.jpg", alt: "Tumpukan sampah di Manado" },
        ],
      },
    ],
  },
  {
    year: 2014,
    activities: [
      {
        id: "climate-reality",
        title: "Climate Reality Project Indonesia",
        titleKey: "trackRecordData.activity.7.title",
        narrativeKey: "trackRecordData.activity.7.narrative",
        location: "Jakarta",
        role: "Peserta",
        era: "tumbuh",
        categories: ["lingkungan", "pendidikan"],
        narrative:
          "Partisipasi dalam kegiatan Climate Reality Project Indonesia di Jakarta. Program pelatihan dan advokasi perubahan iklim yang diprakarsai oleh mantan Wakil Presiden AS Al Gore.",
        photos: [
          { src: "/2014/kegiatan di jakarta Climate Reality Project Indonesia.jpg", alt: "Climate Reality Project Indonesia" },
          { src: "/2014/kegiatan di jakarta Climate Reality Project Indonesia 2.jpg", alt: "Climate Reality Project Indonesia" },
          { src: "/2014/kegiatan di jakarta Climate Reality Project Indonesia 3.jpg", alt: "Climate Reality Project Indonesia" },
        ],
      },
      {
        id: "klabat-lestari-hutan-kenangan",
        title: "Program Klabat Lestari - Hutan Kenangan",
        titleKey: "trackRecordData.activity.8.title",
        narrativeKey: "trackRecordData.activity.8.narrative",
        location: "Gunung Klabat",
        role: "Mitra Pelaksana",
        era: "tumbuh",
        categories: ["lingkungan"],
        capabilities: ["pendampingan-komunitas"],
        narrative:
          "Kegiatan tanam pohon di Hutan Kenangan sebagai bagian dari Program Klabat Lestari. Melibatkan pembuatan kompos dan penanaman pohon di kawasan kaki Gunung Klabat.",
        photos: [
          { src: "/2014/kegiatan tanam pohon di hutan kenangan program klabat lestari.jpg", alt: "Tanam pohon di Hutan Kenangan program Klabat Lestari" },
          { src: "/2014/kegiatan tanam pohon di hutan kenangan program klabat lestari 2.jpg", alt: "Tanam pohon di Hutan Kenangan" },
          { src: "/2014/kegiatan tanam pohon di hutan kenangan program klabat lestari 3.jpg", alt: "Tanam pohon di Hutan Kenangan" },
          { src: "/2014/kegiatan tanam pohon di hutan kenangan program klabat lestari 4.jpg", alt: "Tanam pohon di Hutan Kenangan" },
          { src: "/2014/kegiatan tanam pohon di hutan kenangan program klabat lestari 5.jpg", alt: "Tanam pohon di Hutan Kenangan" },
          { src: "/2014/kegiatan tanam pohon di hutan kenangan program klabat lestari 6.jpg", alt: "Tanam pohon di Hutan Kenangan" },
          { src: "/2014/kegiatan tanam pohon di hutan kenangan program klabat lestari 7.jpg", alt: "Tanam pohon di Hutan Kenangan" },
          { src: "/2014/kegiatan tanam pohon di hutan kenangan program klabat lestari (ember kompos).jpg", alt: "Ember kompos program Klabat Lestari" },
          { src: "/2014/tanam pohon di kaki klabat program klabat lestari.jpg", alt: "Tanam pohon di kaki Klabat" },
          { src: "/2014/tanam pohon di kaki klabat program klabat lestari 2.jpg", alt: "Tanam pohon di kaki Klabat" },
        ],
      },
      {
        id: "penelitian-eceng-gondok",
        title: "Penelitian Eceng Gondok Danau Tondano",
        titleKey: "trackRecordData.activity.9.title",
        narrativeKey: "trackRecordData.activity.9.narrative",
        location: "Danau Tondano",
        role: "Mitra Riset",
        era: "tumbuh",
        categories: ["lingkungan", "pendidikan"],
        narrative:
          "Penelitian eceng gondok di Danau Tondano bersama Groningen University Belanda dan Bank Indonesia. Juga melakukan kunjungan ke lokasi perkebunan organik Rurukan dan pertemuan dengan Lantos Pin dari Groningen University.",
        photos: [
          { src: "/2014/penelititan eceng gondong di dananu tondano audience dengan perwakilan bank indonesia sulawesi utara juga dengan Lantos Pin dari Groningen University Belanda.jpg", alt: "Penelitian eceng gondok Danau Tondano" },
          { src: "/2014/penelititan eceng gondong di dananu tondano audience dengan perwakilan bank indonesia sulawesi utara juga dengan Lantos Pin dari Groningen University Belanda 2.jpg", alt: "Penelitian eceng gondok Danau Tondano" },
          { src: "/2014/penelititan eceng gondong di dananu tondano audience dengan perwakilan bank indonesia sulawesi utara juga dengan Lantos Pin dari Groningen University Belanda beserta lurah desa Tolour.jpg", alt: "Penelitian eceng gondok bersama lurah desa Tolour" },
          { src: "/2014/kunjungan lokasi perkembunan organin Rurukan Lantos Pin dari Groningen University Belanda beserta Harry Gerungan ketua koperasi Edonesia.jpg", alt: "Kunjungan ke perkebunan organik Rurukan" },
          { src: "/2014/kunjungan dari belanda di komunitas Lepra, Kampung Pandu.jpg", alt: "Kunjungan dari Belanda di komunitas Lepra" },
          { src: "/2014/kunjungan dari belanda di komunitas Lepra, Kampung Pandu 2.jpg", alt: "Kunjungan dari Belanda di komunitas Lepra" },
          { src: "/2014/penyulingan pala di minut.jpg", alt: "Penyulingan pala di Minahasa Utara" },
          { src: "/2014/penyulingan pala di minut 2.jpg", alt: "Penyulingan pala di Minahasa Utara" },
        ],
      },
    ],
  },
  {
    year: 2015,
    activities: [
      {
        id: "indonesia-carbon-update",
        title: "Indonesia Carbon Update",
        titleKey: "trackRecordData.activity.10.title",
        narrativeKey: "trackRecordData.activity.10.narrative",
        location: "Manado",
        role: "Peserta",
        era: "tumbuh",
        categories: ["lingkungan", "pendidikan"],
        narrative:
          "Seminar Indonesia Carbon Update bersama Rahmat Witular (mantan Menteri Lingkungan Hidup) dan Steven Sumolang (peneliti antropologi, Ketua Forum Mountenering Sulut).",
        photos: [
          { src: "/2015/Indonesia Carbon Update.jpg", alt: "Indonesia Carbon Update" },
          { src: "/2015/Indonesia Carbon Update bersama rahmat witular mantan menteri lingkungan hidup dan ketua forum mountenering sulut yang juga adalah peneliti antropologi Steven Sumolang.jpg", alt: "Indonesia Carbon Update bersama Rahmat Witular dan Steven Sumolang" },
        ],
      },
      {
        id: "klabat-lestari-2015",
        title: "Sosialisasi Klabat Lestari",
        titleKey: "trackRecordData.activity.11.title",
        narrativeKey: "trackRecordData.activity.11.narrative",
        location: "Gunung Klabat",
        role: "Fasilitator",
        era: "tumbuh",
        categories: ["lingkungan"],
        narrative:
          "Sosialisasi Program Klabat Lestari oleh Green Community Forum Sulawesi Utara untuk memperluas dampak konservasi Gunung Klabat.",
        photos: [
          { src: "/2015/Sosialisasi Program Klabat Lestari  oleh Green Comunity Forum Sulawesi Utara.jpg", alt: "Sosialisasi Program Klabat Lestari" },
        ],
      },
      {
        id: "hpi-outbound",
        title: "Outbound Himpunan Pramuwisata Indonesia",
        titleKey: "trackRecordData.activity.12.title",
        narrativeKey: "trackRecordData.activity.12.narrative",
        location: "Sulawesi Utara",
        role: "Fasilitator",
        era: "tumbuh",
        categories: ["sosial"],
        narrative:
          "Kegiatan outbound pengurus Himpunan Pramuwisata Indonesia (HPI) sebagai bagian dari pengembangan kapasitas organisasi.",
        photos: [
          { src: "/2015/outbong pengurus himpunan pramuwisata indonesia.jpg", alt: "Outbound pengurus HPI" },
          { src: "/2015/outbong pengurus himpunan pramuwisata indonesia 2.jpg", alt: "Outbound pengurus HPI" },
          { src: "/2015/outbong pengurus himpunan pramuwisata indonesia 3.jpg", alt: "Outbound pengurus HPI" },
          { src: "/2015/outbong pengurus himpunan pramuwisata indonesia 4.jpg", alt: "Outbound pengurus HPI" },
        ],
      },
      {
        id: "danau-limboto",
        title: "Dokumentasi Danau Limboto",
        titleKey: "trackRecordData.activity.13.title",
        narrativeKey: "trackRecordData.activity.13.narrative",
        location: "Danau Limboto, Gorontalo",
        role: "Observer",
        era: "tumbuh",
        categories: ["lingkungan"],
        narrative:
          "Dokumentasi pendangkalan Danau Limboto akibat eceng gondok, menjadi salah satu dasar advokasi pengelolaan sampah dan limbah di Sulawesi Utara.",
        photos: [
          { src: "/2015/penangkalan danau limboto akibat eceng gondok.jpg", alt: "Pendangkalan Danau Limboto akibat eceng gondok" },
          { src: "/2015/penangkalan danau limboto akibat eceng gondok 2.jpg", alt: "Pendangkalan Danau Limboto akibat eceng gondok" },
        ],
      },
    ],
  },
  {
    year: 2016,
    activities: [
      {
        id: "tv-polri-sulut",
        title: "Pembentukan TV Polri Sulawesi Utara",
        titleKey: "trackRecordData.activity.14.title",
        narrativeKey: "trackRecordData.activity.14.narrative",
        location: "Sulawesi Utara",
        role: "Peserta",
        era: "meluas",
        categories: ["sosial"],
        capabilities: ["produksi-film"],
        narrative:
          "Rapat pembentukan TV Polri di Sulawesi Utara. Keterlibatan Baciraro dalam forum komunikasi dan pengembangan media kepolisian di wilayah Sulut.",
        photos: [
          { src: "/2016/Rapat pemebentukan TV Polri di Sulawesi Utara.jpg", alt: "Rapat pembentukan TV Polri di Sulawesi Utara" },
          { src: "/2016/Rapat pemebentukan TV Polri di Sulawesi Utara 2.jpg", alt: "Rapat pembentukan TV Polri di Sulawesi Utara" },
          { src: "/2016/Rapat pemebentukan TV Polri di Sulawesi Utara 3.jpg", alt: "Rapat pembentukan TV Polri di Sulawesi Utara" },
          { src: "/2016/Rapat pemebentukan TV Polri di Sulawesi Utara 4.jpg", alt: "Rapat pembentukan TV Polri di Sulawesi Utara" },
        ],
      },
    ],
  },
  {
    year: 2017,
    activities: [
      {
        id: "taponesia",
        title: "Aplikasi Tanam Pohon Taponesia",
        titleKey: "trackRecordData.activity.15.title",
        narrativeKey: "trackRecordData.activity.15.narrative",
        location: "Manado",
        role: "Developer Teknologi",
        era: "meluas",
        categories: ["teknologi", "lingkungan"],
        capabilities: ["pengembangan-sistem-digital"],
        featured: true,
        narrative:
          "Pengembangan aplikasi tanam pohon Taponesia dengan fitur dashboard, social wall, dan menu profile. Inovasi digital untuk memantau kegiatan penghijauan dan reboisasi.",
        photos: [
          { src: "/2017/ dashboard Aplikasi tanam pohon Taponesia.jpg", alt: "Dashboard Aplikasi Tanam Pohon Taponesia" },
          { src: "/2017/Aplikasi tanam pohon Social Wall.jpg", alt: "Social Wall aplikasi tanam pohon" },
          { src: "/2017/Aplikasi tanam pohon Social Wall 2.jpg", alt: "Social Wall aplikasi tanam pohon" },
          { src: "/2017/menu profile Aplikasi tanam pohon.jpg", alt: "Menu profile aplikasi tanam pohon" },
        ],
      },
      {
        id: "green-community-forum",
        title: "Green Community Forum Tanam Pohon",
        titleKey: "trackRecordData.activity.16.title",
        narrativeKey: "trackRecordData.activity.16.narrative",
        location: "Minahasa Utara",
        role: "Mitra Pelaksana",
        era: "meluas",
        categories: ["lingkungan", "sosial"],
        narrative:
          "Aksi tanam pohon oleh Green Community Forum Minahasa Utara. Melibatkan identifikasi pohon dan penanaman di berbagai lokasi di wilayah Minahasa Utara.",
        photos: [
          { src: "/2017/Green Comunitiy Forum Minahasa Utara.jpg", alt: "Green Community Forum Minahasa Utara" },
          { src: "/2017/Green Comunity Forum tanam pohon.jpg", alt: "GCF tanam pohon" },
          { src: "/2017/Green Comunity Forum tanam pohon 2.jpg", alt: "GCF tanam pohon" },
          { src: "/2017/Green Comunity Forum tanam pohon 5.jpg", alt: "GCF tanam pohon" },
          { src: "/2017/Green Comunity Forum tanam pohon 8.jpg", alt: "GCF tanam pohon" },
          { src: "/2017/Green Comunity Forum tanam pohon (identifikasi pohon).jpg", alt: "Identifikasi pohon" },
        ],
      },
      {
        id: "smash",
        title: "Aplikasi Bank Sampah SMASH",
        titleKey: "trackRecordData.activity.17.title",
        narrativeKey: "trackRecordData.activity.17.narrative",
        location: "Manado",
        role: "Fasilitator Teknologi",
        era: "meluas",
        categories: ["teknologi", "lingkungan", "ekonomi"],
        capabilities: ["pengembangan-sistem-digital"],
        narrative:
          "Pengembangan aplikasi bank sampah online SMASH. Fasilitasi implementasi sistem bank sampah digital di Kota Manado untuk integrasi dengan sistem non-tunai.",
        photos: [
          { src: "/2017/aplikasi bank sampah SMASH.jpg", alt: "Aplikasi bank sampah SMASH" },
          { src: "/2017/aplikasi bank sampah SMASH 2.jpg", alt: "Aplikasi bank sampah SMASH" },
          { src: "/2017/aplikasi bank sampah SMASH 3.jpg", alt: "Aplikasi bank sampah SMASH" },
        ],
      },
      {
        id: "agape",
        title: "Launching Bank Sampah Agape",
        titleKey: "trackRecordData.activity.18.title",
        narrativeKey: "trackRecordData.activity.18.narrative",
        location: "Desa Tumaluntung, Kauditan",
        role: "Fasilitator",
        era: "meluas",
        categories: ["lingkungan", "sosial", "ekonomi"],
        capabilities: ["pendampingan-komunitas", "pemberdayaan-perempuan"],
        narrative:
          "Launching Bank Sampah Agape di Desa Tumaluntung, Kecamatan Kauditan. Pendirian bank sampah berbasis komunitas untuk pengelolaan sampah di tingkat desa.",
        photos: [
          { src: "/2017/kantor pemasaran bank sampah agape.jpg", alt: "Kantor pemasaran bank sampah Agape" },
          { src: "/2017/launching bank sampah agape di desa tumaluntung.jpg", alt: "Launching bank sampah Agape di Desa Tumaluntung" },
          { src: "/2017/launching bank sampah agape di desa tumaluntung 2.jpg", alt: "Launching bank sampah Agape" },
          { src: "/2017/launching bank sampah agape di desa tumaluntung 3.jpg", alt: "Launching bank sampah Agape" },
          { src: "/2017/launching bank sampah agape di desa tumaluntung 4.jpg", alt: "Launching bank sampah Agape" },
          { src: "/2017/launching bank sampah agape di desa tumaluntung 5.jpg", alt: "Launching bank sampah Agape" },
          { src: "/2017/launching bank sampah agape di desa tumaluntung 6.jpg", alt: "Launching bank sampah Agape" },
        ],
      },
      {
        id: "danone-2017",
        title: "Meeting Danone Jakarta",
        titleKey: "trackRecordData.activity.19.title",
        narrativeKey: "trackRecordData.activity.19.narrative",
        location: "Jakarta",
        role: "Mitra",
        era: "meluas",
        categories: ["lingkungan", "ekonomi"],
        narrative:
          "Pertemuan dengan Danone Pusat di Jakarta untuk menjajaki kerjasama pengelolaan sampah dan program bijak berplastik di Sulawesi Utara.",
        photos: [
          { src: "/2017/kunjungan danone pusat di jakarta 3.jpg", alt: "Kunjungan Danone Pusat di Jakarta" },
          { src: "/2017/meeting dengan danone pusat di jakarta.jpg", alt: "Meeting dengan Danone Pusat" },
          { src: "/2017/meeting dengan danone pusat di jakarta 2.jpg", alt: "Meeting dengan Danone Pusat" },
          { src: "/2017/meeting dengan danone pusat di jakarta 4.jpg", alt: "Meeting dengan Danone Pusat" },
        ],
      },
      {
        id: "pinili",
        title: "Program Pertanian Desa Pinili",
        titleKey: "trackRecordData.activity.20.title",
        narrativeKey: "trackRecordData.activity.20.narrative",
        location: "Desa Pinili, Dimembe",
        role: "Pendamping",
        era: "meluas",
        categories: ["lingkungan", "ekonomi"],
        capabilities: ["pengelolaan-sampah-organik"],
        narrative:
          "Program pembibitan dan pertanian di Desa Pinili. Meliputi pembibitan rica (cabai), penyemaian, dan penanaman padi sebagai bagian dari pengembangan pertanian berkelanjutan.",
        photos: [
          { src: "/2017/padi di pinili.jpg", alt: "Padi di Pinili" },
          { src: "/2017/panen padi di pinili.jpg", alt: "Panen padi di Pinili" },
          { src: "/2017/panen padi di pinili 2.jpg", alt: "Panen padi di Pinili" },
          { src: "/2017/panen padi di pinili 3.jpg", alt: "Panen padi di Pinili" },
          { src: "/2017/pembibitan rica di rumah bibit rica desa pinili.jpg", alt: "Pembibitan rica di Pinili" },
          { src: "/2017/penyemaian bibit rica di pinili .jpg", alt: "Penyemaian bibit rica di Pinili" },
          { src: "/2017/penyiapan pembibitan di pinili.jpg", alt: "Penyiapan pembibitan di Pinili" },
          { src: "/2017/rumah bibit rica desa pinili.jpg", alt: "Rumah bibit rica Desa Pinili" },
        ],
      },
    ],
  },
  {
    year: 2018,
    activities: [
      {
        id: "bank-sampah-simfoni",
        title: "Bank Sampah Simfoni",
        titleKey: "trackRecordData.activity.21.title",
        narrativeKey: "trackRecordData.activity.21.narrative",
        location: "Manado",
        role: "Fasilitator",
        era: "meluas",
        categories: ["lingkungan", "sosial", "ekonomi"],
        capabilities: ["pendampingan-komunitas"],
        narrative:
          "Pencanangan Bank Sampah Simfoni di Festival Paskah dan pengembangan bank sampah jemaat untuk menunjang pariwisata di Sulawesi Utara. Bank sampah ini menjadi pusat pengumpulan dan pemilahan sampah berbasis komunitas.",
        photos: [
          { src: "/2018/Bank Sampah Simfoni di Festival paskah dan pencanangan bank sampah jemaat menunjang pariwisata sulut.jpg", alt: "Bank Sampah Simfoni di Festival Paskah" },
          { src: "/2018/Bank Sampah Simfoni di Festival paskah dan pencanangan bank sampah jemaat menunjang pariwisata sulut 2.jpg", alt: "Bank Sampah Simfoni" },
          { src: "/2018/Festival paskah dan pencanangan bank sampah jemaat menunjang pariwisata sulut (menjadi narasumber).jpg", alt: "Narasumber Festival Paskah" },
          { src: "/2018/penjualan sampah di bank sampah simponi.jpg", alt: "Penjualan sampah di bank sampah Simfoni" },
          { src: "/2018/perkembangan dashboard bank sampah.png", alt: "Perkembangan dashboard bank sampah" },
        ],
      },
      {
        id: "sma-7-adiwiyata",
        title: "Program Adiwiyata SMA Negeri 7 Manado",
        titleKey: "trackRecordData.activity.22.title",
        narrativeKey: "trackRecordData.activity.22.narrative",
        location: "Manado",
        role: "Pendamping",
        era: "meluas",
        categories: ["pendidikan", "lingkungan"],
        capabilities: ["edukasi-lingkungan", "pengelolaan-sampah-organik"],
        narrative:
          "Pendampingan SMA Negeri 7 Manado menuju Sekolah Adiwiyata Mandiri. Meliputi launching bank sampah, pembuatan komposter, pengomposan, dan edukasi pengelolaan sampah di lingkungan sekolah. Berhasil meraih penghargaan Sekolah Adiwiyata Mandiri.",
        photos: [
          { src: "/2018/Bank Sampah di SMA 7 Manado.jpg", alt: "Bank Sampah di SMA 7 Manado" },
          { src: "/2018/launching dan pelatihan Bank Sampah Adiwiyata di SMA 7 Manado.jpg", alt: "Launching bank sampah Adiwiyata SMA 7" },
          { src: "/2018/launching dan pelatihan Bank Sampah Adiwiyata di SMA 7 Manado 4.jpg", alt: "Pelatihan bank sampah Adiwiyata" },
          { src: "/2018/penghargaan Sekolah Adiwiyata Mandiri SMA Negeri 7 Manado.jpg", alt: "Penghargaan Adiwiyata Mandiri SMA 7" },
          { src: "/2018/komposter di SMA Negeri 7 Manado.jpg", alt: "Komposter di SMA 7 Manado" },
        ],
      },
      {
        id: "tpa-sumompo",
        title: "Kunjungan TPA Sumompo",
        titleKey: "trackRecordData.activity.23.title",
        narrativeKey: "trackRecordData.activity.23.narrative",
        location: "Manado",
        role: "Observer",
        era: "meluas",
        categories: ["lingkungan"],
        narrative:
          "Kunjungan ke Tempat Pemrosesan Akhir (TPA) Sumompo untuk mempelajari sistem pengelolaan sampah dan berdiskusi dengan Koperasi CELS mengenai potensi pengembangan daur ulang.",
        photos: [
          { src: "/2018/Kunjungan di TPA Sumompo.jpg", alt: "Kunjungan di TPA Sumompo" },
          { src: "/2018/Kunjungan di TPA Sumompo 4.jpg", alt: "Kunjungan di TPA Sumompo" },
          { src: "/2018/Kunjungan di TPA Sumompo dengan ketua Koperasi CELS.jpg", alt: "Kunjungan TPA Sumompo dengan Koperasi CELS" },
        ],
      },
      {
        id: "siladen-resort",
        title: "Pengelolaan Sampah di Siladen Resort",
        titleKey: "trackRecordData.activity.24.title",
        narrativeKey: "trackRecordData.activity.24.narrative",
        location: "Pulau Siladen",
        role: "Fasilitator",
        era: "meluas",
        categories: ["lingkungan", "ekonomi"],
        capabilities: ["pengelolaan-sampah-wisata"],
        narrative:
          "Pelatihan pengolahan sampah pada karyawan di Siladen Resort dan workshop waste management and circular economy. Inisiatif pemanfaatan botol wine bekas menjadi gelas dan produk bernilai tambah di kawasan wisata.",
        photos: [
          { src: "/2018/Pelatihan pengolahan sampah pada karyawan di siladen resort.jpg", alt: "Pelatihan pengolahan sampah di Siladen Resort" },
          { src: "/2018/pemanfaatan botol wine jadi gelas di siladen resort.jpg", alt: "Pemanfaatan botol wine jadi gelas" },
          { src: "/2018/pemanfaatan botol wine jadi gelas di siladen resort 2.jpg", alt: "Pemanfaatan botol wine jadi gelas" },
          { src: "/2018/workshop waste management and circular economic di pulau siladen.jpg", alt: "Workshop waste management di Siladen" },
        ],
      },
      {
        id: "koperasi-cels",
        title: "Koperasi Celebes Energi Lestari (CELS)",
        titleKey: "trackRecordData.activity.25.title",
        narrativeKey: "trackRecordData.activity.25.narrative",
        location: "Manado",
        role: "Inisiator",
        era: "meluas",
        categories: ["lingkungan", "ekonomi"],
        capabilities: ["daur-ulang-plastik"],
        featured: true,
        narrative:
          "Pengembangan Koperasi CELS sebagai koperasi bank sampah pertama di Sulawesi Utara. Menjajaki kerjasama pengelolaan sampah rumah sakit dengan RS Siloam dan kunjungan ke Pertamina Geothermal untuk sinergi pengelolaan sampah.",
        photos: [
          { src: "/2018/koperasi bank sampah pertama di sulur Celebes Energi Lestari.jpg", alt: "Koperasi bank sampah pertama CELS" },
          { src: "/2018/koperasi CELS berkunjung ke RS Siloam untuk menjajaki kerjasama sampah Rumah Sakit.jpg", alt: "Kunjungan CELS ke RS Siloam" },
          { src: "/2018/koperasi CELS berkunjung ke RS Siloam untuk menjajaki kerjasama sampah Rumah Sakit 5.jpg", alt: "Kunjungan CELS ke RS Siloam" },
          { src: "/2018/kunjungan Koperasi CELS ke Pertamina Geotermal.jpg", alt: "Kunjungan CELS ke Pertamina Geothermal" },
          { src: "/2018/rapat bersama tim Pertamina Geotermal Lahendong.jpg", alt: "Rapat bersama Pertamina Geothermal" },
        ],
      },
      {
        id: "bank-sampah-adipura-bitung",
        title: "Bank Sampah Adipura Bitung",
        titleKey: "trackRecordData.activity.26.title",
        narrativeKey: "trackRecordData.activity.26.narrative",
        location: "Bitung",
        role: "Fasilitator",
        era: "meluas",
        categories: ["lingkungan", "sosial"],
        capabilities: ["pendampingan-komunitas"],
        narrative:
          "Pembentukan bank sampah Adipura di Kota Bitung untuk mendukung program kebersihan dan penghijauan kota. Meliputi sosialisasi, pendirian, dan operasional bank sampah.",
        photos: [
          { src: "/2018/pembentukan bank sampah Adipura Bitung.jpg", alt: "Pembentukan bank sampah Adipura Bitung" },
          { src: "/2018/pembentukan bank sampah Adipura Bitung 3.jpg", alt: "Pembentukan bank sampah Adipura Bitung" },
          { src: "/2018/penimbangan Bank Sampah Adipura Bitung.jpg", alt: "Penimbangan bank sampah Adipura Bitung" },
          { src: "/2018/penimbangan Bank Sampah Adipura Bitung 2.jpg", alt: "Penimbangan bank sampah Adipura Bitung" },
        ],
      },
      {
        id: "pilah-sampah-pulau-bangka",
        title: "Pemilahan Sampah Pulau Bangka",
        titleKey: "trackRecordData.activity.27.title",
        narrativeKey: "trackRecordData.activity.27.narrative",
        location: "Pulau Bangka",
        role: "Mitra",
        era: "meluas",
        categories: ["lingkungan"],
        capabilities: ["pengelolaan-sampah-pesisir"],
        narrative:
          "Kegiatan pemilahan sampah dari laut Pulau Bangka bekerja sama dengan Bangka Conservation Foundation. Upaya mengurangi pencemaran sampah plastik di kawasan konservasi laut.",
        photos: [
          { src: "/2018/pilah sampah dari laur pulau bangka.jpg", alt: "Pilah sampah dari Pulau Bangka" },
          { src: "/2018/pilah sampah dari laur pulau bangka 3.jpg", alt: "Pilah sampah dari Pulau Bangka" },
          { src: "/2018/pilah sampah dari laur pulau bangka 5.jpg", alt: "Pilah sampah dari Pulau Bangka" },
          { src: "/2018/pilah sampah dari laur pulau bangka 8.jpg", alt: "Pilah sampah dari Pulau Bangka" },
          { src: "/2018/sampah dari bangka converation fondation.jpg", alt: "Sampah dari Bangka Conservation Foundation" },
        ],
      },
      {
        id: "teknologi-daur-ulang",
        title: "Pengembangan Teknologi Daur Ulang",
        titleKey: "trackRecordData.activity.28.title",
        narrativeKey: "trackRecordData.activity.28.narrative",
        location: "Manado",
        role: "Inisiator",
        era: "meluas",
        categories: ["teknologi", "lingkungan"],
        capabilities: ["daur-ulang-plastik"],
        narrative:
          "Pengembangan alat penyulingan sampah plastik menjadi BBM dan pembuatan batako dari residu sampah plastik. Kolaborasi dengan Politeknik Negeri Manado untuk pembuatan mesin pencacah sampah.",
        photos: [
          { src: "/2018/alat penyulingan sampah plastik menjadi bbm.jpg", alt: "Alat penyulingan sampah plastik menjadi BBM" },
          { src: "/2018/bbm dari sampah plastik.jpg", alt: "BBM dari sampah plastik" },
          { src: "/2018/residu sampah plastik menjadi batako.jpg", alt: "Residu sampah plastik menjadi batako" },
          { src: "/2018/di undang unutk meninjau tugas akhir mahasiswa teknik politeknik negeri manado mesin membuat mesin cacah.jpg", alt: "Tinjau tugas akhir mesin cacah Politeknik" },
        ],
      },
    ],
  },
  {
    year: 2019,
    activities: [
      {
        id: "sofa-ecobrick",
        title: "Produksi Sofa Ecobrick",
        titleKey: "trackRecordData.activity.29.title",
        narrativeKey: "trackRecordData.activity.29.narrative",
        location: "Manado",
        role: "Produsen",
        era: "meluas",
        categories: ["lingkungan", "ekonomi"],
        capabilities: ["daur-ulang-plastik", "strategi-kreatif"],
        featured: true,
        narrative:
          "Inovasi pembuatan sofa dari ecobrick (botol plastik bekas). Produk furnitur ramah lingkungan yang menjadi ikon Baciraro dalam ekonomi sirkular dan daur ulang sampah plastik.",
        photos: [
          { src: "/2019/4 sofa ecobrick.jpg", alt: "4 sofa ecobrick" },
          { src: "/2019/pembuatan sofa ecobrick.jpg", alt: "Pembuatan sofa ecobrick" },
          { src: "/2019/pembuatan sofa ecobrick 2.jpg", alt: "Pembuatan sofa ecobrick" },
          { src: "/2019/sofa ecobrick.jpg", alt: "Sofa ecobrick" },
          { src: "/2019/Ketua koperasi CELLS duduk di sofa ecobrick.jpg", alt: "Ketua CELS duduk di sofa ecobrick" },
          { src: "/2019/hasil pembuatan sofa ecobrick .jpg", alt: "Hasil pembuatan sofa ecobrick" },
        ],
      },
      {
        id: "griffith-university",
        title: "Kunjungan Griffith University Australia",
        titleKey: "trackRecordData.activity.30.title",
        narrativeKey: "trackRecordData.activity.30.narrative",
        location: "Manado",
        role: "Tuan Rumah",
        era: "meluas",
        categories: ["pendidikan", "lingkungan"],
        narrative:
          "Kunjungan Prof Noel Scott dari Griffith University Australia ke Bank Sampah Simfoni dan Politeknik Negeri Manado. Study tentang sustainable tourism dan pengelolaan sampah berkelanjutan di kawasan wisata.",
        photos: [
          { src: "/2019/kunjungan Prof Noel Scoth dari Grifith University Australi ke bank sampah simfoni.jpg", alt: "Kunjungan Prof Noel Scott ke bank sampah Simfoni" },
          { src: "/2019/kunjungan Prof Noel Scoth dari Grifith University Australi ke bank sampah simfoni 2.jpg", alt: "Kunjungan Prof Noel Scott" },
          { src: "/2019/kunjungan Prof Noel Scoth dari Grifith University Australi ke bank sampah simfoni 4.jpg", alt: "Kunjungan Prof Noel Scott" },
          { src: "/2019/kunjungan Prof Noel Spot dari Grifith Univesity Australi di Politeknik Negeri Manado.jpg", alt: "Kunjungan Prof Noel Scott di Politeknik" },
          { src: "/2018/Study Sustainable Tourism di Griffith University .jpg", alt: "Study Sustainable Tourism di Griffith University" },
        ],
      },
      {
        id: "lukisan-plastik",
        title: "Kreasi Lukisan dan Karya dari Sampah Plastik",
        titleKey: "trackRecordData.activity.31.title",
        narrativeKey: "trackRecordData.activity.31.narrative",
        location: "Manado",
        role: "Produsen",
        era: "meluas",
        categories: ["lingkungan", "ekonomi"],
        capabilities: ["strategi-kreatif"],
        narrative:
          "Pengolahan sampah plastik dan handuk bekas menjadi karya seni lukisan dan produk kreatif. Inovasi daur ulang yang mengubah limbah menjadi produk bernilai seni tinggi.",
        photos: [
          { src: "/2019/hasil lukisan dari sampah plastik.jpg", alt: "Lukisan dari sampah plastik" },
          { src: "/2019/hasil lukisan dari sampah plastik 2.jpg", alt: "Lukisan dari sampah plastik" },
          { src: "/2019/hasil lukisan dari sampah plastik 3.jpg", alt: "Lukisan dari sampah plastik" },
          { src: "/2019/hasil pengolahan sampah menjadi lukisan alam.jpg", alt: "Lukisan alam dari sampah" },
          { src: "/2019/hasil kreasi sampah plastik dan handuk bekas menjadi lukisan.jpg", alt: "Kreasi sampah plastik dan handuk bekas" },
        ],
      },
      {
        id: "apsi",
        title: "Musyawarah Nasional APSI",
        titleKey: "trackRecordData.activity.32.title",
        narrativeKey: "trackRecordData.activity.32.narrative",
        location: "Jakarta",
        role: "Anggota",
        era: "meluas",
        categories: ["lingkungan", "ekonomi"],
        narrative:
          "Partisipasi dalam Musyawarah Nasional Asosiasi Pengusaha Sampah Indonesia (APSI) dan menjadi bagian dari pengurus organisasi pengusaha daur ulang plastik Indonesia.",
        photos: [
          { src: "/2019/musyawarah nasional pengurus APSI.jpg", alt: "Munas APSI" },
          { src: "/2019/musyawarah nasional pengurus APSI 2.jpg", alt: "Munas APSI" },
          { src: "/2019/memakai baju APSI Asosiasi Pengusaha Sampah Indonesia di bank sampah simfoni .jpg", alt: "Baju APSI di bank sampah Simfoni" },
          { src: "/2019/pengiriman dokumen pengurus dokumen APSI.jpg", alt: "Pengiriman dokumen APSI" },
        ],
      },
      {
        id: "bank-sampah-simfoni-2019",
        title: "Operasional Bank Sampah Simfoni",
        titleKey: "trackRecordData.activity.33.title",
        narrativeKey: "trackRecordData.activity.33.narrative",
        location: "Manado",
        role: "Pengelola",
        era: "meluas",
        categories: ["lingkungan", "sosial", "ekonomi"],
        narrative:
          "Kegiatan operasional Bank Sampah Simfoni meliputi pemilahan botol plastik, penimbangan, penyerahan buku tabungan nasabah, dan pengelolaan sampah harian. Bank sampah ini menjadi pusat ekonomi sirkular berbasis komunitas.",
        photos: [
          { src: "/2019/hasil pemilahan botol plastik di bank samapah simfoni.jpg", alt: "Hasil pemilahan botol plastik di bank sampah Simfoni" },
          { src: "/2019/pemilahan botol plastik di bank samapah simfoni.jpg", alt: "Pemilahan botol plastik" },
          { src: "/2019/tim pemilah sampah bank sampah simfoni.jpg", alt: "Tim pemilah sampah" },
          { src: "/2019/penyerahan buku nasabah di bank sampah simfoni.jpg", alt: "Penyerahan buku nasabah" },
          { src: "/2019/mesin press di bank sampah simfoni.jpg", alt: "Mesin press di bank sampah Simfoni" },
        ],
      },
      {
        id: "handuk-bekas-craft",
        title: "Kerajinan dari Handuk Bekas",
        titleKey: "trackRecordData.activity.34.title",
        narrativeKey: "trackRecordData.activity.34.narrative",
        location: "Manado",
        role: "Produsen",
        era: "meluas",
        categories: ["lingkungan", "ekonomi"],
        capabilities: ["strategi-kreatif", "pemberdayaan-perempuan"],
        narrative:
          "Inovasi daur ulang handuk bekas menjadi pot, anting-anting, dan berbagai produk kerajinan. Program pemberdayaan masyarakat melalui kreativitas daur ulang tekstil.",
        photos: [
          { src: "/2019/anting-anting dari sampah plastik.jpg", alt: "Anting-anting dari sampah plastik" },
          { src: "/2019/pot dari handuk bekas.jpg", alt: "Pot dari handuk bekas" },
          { src: "/2019/pembuatan pot dari handuk bekas.jpg", alt: "Pembuatan pot dari handuk bekas" },
          { src: "/2019/hasil dari handuk bekas.jpg", alt: "Hasil dari handuk bekas" },
          { src: "/2019/pot dari handuk bekas 2.jpg", alt: "Pot dari handuk bekas" },
        ],
      },
      {
        id: "media-2019",
        title: "Liputan Media dan Diskusi Publik",
        titleKey: "trackRecordData.activity.35.title",
        narrativeKey: "trackRecordData.activity.35.narrative",
        location: "Manado",
        role: "Narasumber",
        era: "meluas",
        categories: ["lingkungan", "pendidikan"],
        capabilities: ["edukasi-lingkungan"],
        narrative:
          "Menjadi narasumber di Kompas TV Sapa Manado dengan tema 'Manado dan Sampah', serta diskusi tentang banjir di TVRI. Media coverage dan edukasi publik tentang pengelolaan sampah.",
        photos: [
          { src: "/2019/menjadi narasumber di kompas tv sapa manado dengan tema Manado dan Sampah.jpg", alt: "Narasumber Kompas TV" },
          { src: "/2019/menjadi narasumber di kompas tv sapa manado dengan tema Manado dan Sampah 2.jpg", alt: "Narasumber Kompas TV" },
          { src: "/2019/peliputan media kompas tv di bank sampah simfoni.jpg", alt: "Liputan Kompas TV di bank sampah Simfoni" },
          { src: "/2019/diskusi tentang banjir manado di tvri.jpg", alt: "Diskusi banjir Manado di TVRI" },
        ],
      },
      {
        id: "pameran-ais",
        title: "Pameran AIS dan Event Kelautan",
        titleKey: "trackRecordData.activity.36.title",
        narrativeKey: "trackRecordData.activity.36.narrative",
        location: "Manado",
        role: "Peserta",
        era: "meluas",
        categories: ["lingkungan", "pendidikan"],
        narrative:
          "Partisipasi dalam pameran AIS (Archipelagic and Island States) dengan peneliti kelautan dari seluruh dunia. Memperkenalkan inovasi pengelolaan sampah dan bank sampah kepada komunitas internasional.",
        photos: [
          { src: "/2019/pameran AIS dengan peneliti kelautan di seluruh dunia.jpg", alt: "Pameran AIS" },
          { src: "/2019/pameran AIS dengan peneliti kelautan di seluruh dunia 2.jpg", alt: "Pameran AIS" },
          { src: "/2019/kunjungan dari DLH provinsi ke stand bank sampah di event AIS.jpg", alt: "Kunjungan DLH ke stand bank sampah di AIS" },
        ],
      },
      {
        id: "sosialisasi-pge-2019",
        title: "Sosialisasi Bank Sampah bersama PGE",
        titleKey: "trackRecordData.activity.37.title",
        narrativeKey: "trackRecordData.activity.37.narrative",
        location: "PADIOR, Minahasa",
        role: "Fasilitator",
        era: "meluas",
        categories: ["lingkungan", "sosial"],
        capabilities: ["pendampingan-komunitas"],
        narrative:
          "Sosialisasi program bank sampah bersama Pertamina Geothermal Energy di PADIOR. Edukasi pemilahan sampah dan pendirian bank sampah di wilayah operasional PGE.",
        photos: [
          { src: "/2019/sosialisasi program bank sampah dengan PGE di PADIOR.jpg", alt: "Sosialisasi PGE di PADIOR" },
          { src: "/2019/sosialisasi program bank sampah dengan PGE di PADIOR 2.jpg", alt: "Sosialisasi PGE di PADIOR" },
          { src: "/2019/sosialisasi program bank sampah dengan PGE di PADIOR 3.jpg", alt: "Sosialisasi PGE di PADIOR" },
        ],
      },
    ],
  },
  {
    year: 2020,
    activities: [
      {
        id: "kompetisi-1000-startup-digital",
        title: "Kompetisi 1000 Startup Digital",
        titleKey: "trackRecordData.activity.38.title",
        narrativeKey: "trackRecordData.activity.38.narrative",
        location: "Manado",
        role: "Peserta",
        era: "transformasi",
        categories: ["teknologi", "lingkungan", "ekonomi"],
        capabilities: ["pengembangan-sistem-digital"],
        featured: true,
        narrative:
          "Baciraro Recycle memperkenalkan diri sebagai startup digital inovasi pengelolaan sampah di sumber, termasuk bank sampah berbasis digital dan ekosistem circular economy. Program nasional Kementerian Kominfo RI.",
        highlights: [
          "Inovasi teknologi untuk pengelolaan sampah",
          "Bank Sampah berbasis digital",
          "Akselerasi pembangunan daerah",
        ],
        photos: [
          { src: "/2020/FB_IMG_1589974017576.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1589974027874.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1591150551529.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1591150583569.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1593993885887.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1595766811275.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1597115115501.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1597121669768.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1597121722925.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1597121730048.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1597121741335.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1597121748596.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1597121784549.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1597121807338.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1597121827513.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1597121831479.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1597121835793.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1599474421673.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/FB_IMG_1600252436662.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200110_075907.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200111_131604.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200118_113845.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200119_164405.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200120_145505.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200129_095020.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200310_120311.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200312_125003.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200312_142437.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200312_150235.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200312_151352.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200317_202747.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200317_202826.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200320_100110.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200416_105021.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200418_103406.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200421_183451.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200427_142806.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200427_142844.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200501_163703.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200502_121202.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200502_121403.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200502_130938.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200502_131834.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200506_103614.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200509_195600.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200516_112537.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200519_115643.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200519_115709.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200519_115909.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200520_161154.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200520_161223.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200520_183615.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200520_183625.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200520_183747.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200523_113032.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200526_222749.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200531_123922.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200531_125001.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200606_103005.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200606_103016.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200606_103029.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200606_103323.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200606_103340.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200606_103438.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200606_144055.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200609_093339.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200614_165430_BURST1.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200615_090723.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200616_104809.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200616_110956.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200616_134415_BURST1.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200624_210201.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200628_190417.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200629_120337.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200630_105146.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200630_114840.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200630_115246.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200630_141449.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200701_111937.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200702_090014.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200702_155102.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200705_144348.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200705_151427.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200705_155447.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200705_155507.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200706_193314.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200708_171042.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200716_084436.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200719_120501.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200725_110130.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200807_171353.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200823_161955.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200902_132920.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200905_120659.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20200927_175231.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20201018_150339.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20201027_165035.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20201031_172454.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20201031_172702.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/IMG_20201121_132829.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/Screenshot_2020-06-22-21-48-14-865_us.zoom.videomeetings.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/Screenshot_2020-07-20-17-14-32-717_us.zoom.videomeetings.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/Screenshot_2020-07-20-17-28-49-060_us.zoom.videomeetings.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/Screenshot_2020-07-20-17-34-43-999_us.zoom.videomeetings.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/Screenshot_2020-07-20-17-43-00-037_us.zoom.videomeetings.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/Screenshot_2020-07-23-17-08-45-992_us.zoom.videomeetings.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/Screenshot_2020-07-23-17-49-17-373_us.zoom.videomeetings.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/Screenshot_2020-07-26-19-36-15-785_us.zoom.videomeetings.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/Screenshot_2020-09-24-17-38-24-853_us.zoom.videomeetings.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/Screenshot_2020-09-24-17-38-28-556_us.zoom.videomeetings.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/Screenshot_2020-10-04-21-34-15-412_us.zoom.videomeetings.jpg", alt: "Kegiatan 2020" },
          { src: "/2020/Screenshot_2020-11-11-15-51-09-662_us.zoom.videomeetings.jpg", alt: "Kegiatan 2020" },
        ],
      },
    ],
  },
  {
    year: 2021,
    activities: [
      {
        id: "plastic-brick",
        title: "Project Batako dari Sampah Plastik",
        titleKey: "trackRecordData.activity.39.title",
        narrativeKey: "trackRecordData.activity.39.narrative",
        location: "Pulau Siladen",
        role: "Eksekutor",
        era: "transformasi",
        categories: ["teknologi", "lingkungan"],
        capabilities: ["daur-ulang-plastik", "pengelolaan-sampah-pesisir"],
        narrative:
          "Plastic Brick, project kerjasama dengan Trash Waste Solution untuk pembuatan batako plastik dari sampah plastik dengan isu mengurangi dampak pencemaran sampah plastik di laut, terhubung dengan aktivitas antara team Trash Waste Solution di Pulau Siladen dengan Baciraro Recycle. Diproduksi dengan mesin standar Precious Plastic.",
        highlights: [
          "Pengurangan sampah plastik di laut",
          "Inovasi batako dari plastik bekas",
          "Dukungan Ocean Hero",
          "Mesin standar Precious Plastic",
        ],
        photos: [
          { src: "/2021/FB_IMG_1614083380576.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1614554563302.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1614642061910.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1614994443664.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1615537952158.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1616197658076.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1616224080820.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1616224102124.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1616638044995.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1617950928322.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1618445137254.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1618451936879.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1618615982967.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1619920904024.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1620030228480.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1620032237504.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1620277410605.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1620520775771.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1620520784410.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1620520787091.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1621900934741.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1622093938583.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1622194912234.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1623126320251.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1623412769902.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1624667093435.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1624690785039.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1628213967759.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1628247602997.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1630457136527.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1630457142181.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1630889678414.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1631332991343.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1631526527213.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1631526530204.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1632216689349.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1633037451661.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1634367818632.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1635413121673.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1635413124651.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1635413127952.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1636613255704.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/FB_IMG_1636626587287.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG-20210501-WA0107.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20210225_082833.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20210327_143336.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20210327_162212.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20210410_164745.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20210415_101815.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20210420_135722.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20210428_140559.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20210430_094110.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20210501_094144.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20210522_175311.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20210522_175415.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20210806_151608.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20211019_105626.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20211204_114304.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20211205_185954.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20211205_190009.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20211216_150742.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20211218_095107.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20211219_163352.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20211219_163412.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/IMG_20211219_163421.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-02-23-20-03-09-296_com.facebook.katana.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-02-26-08-41-16-755_com.facebook.katana.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-02-26-08-41-39-230_com.facebook.katana.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-02-28-20-22-28-383_com.skype.raider.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-04-03-19-03-09-626_com.skype.raider.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-04-10-18-13-42-380_com.google.android.youtube.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-04-29-18-53-08-463_com.skype.raider.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-04-30-14-18-02-284_com.skype.raider.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-06-15-20-16-59-557_us.zoom.videomeetings.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-06-17-10-56-15-523_us.zoom.videomeetings.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-08-11-15-47-40-277_com.skype.raider.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-10-15-16-22-00-133_com.microsoft.teams.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-10-15-16-44-03-100_com.microsoft.teams.jpg", alt: "Kegiatan 2021" },
          { src: "/2021/Screenshot_2021-10-15-21-08-30-539_com.google.android.apps.docs.jpg", alt: "Kegiatan 2021" },
        ],
      },
    ],
  },
  {
    year: 2022,
    activities: [
      {
        id: "bank-sampah-setor-jo",
        title: "Program Bank Sampah Setor Jo & Eco-Enzyme",
        titleKey: "trackRecordData.activity.40.title",
        narrativeKey: "trackRecordData.activity.40.narrative",
        location: "Minahasa",
        role: "Eksekutor",
        era: "transformasi",
        categories: ["lingkungan", "sosial", "ekonomi"],
        capabilities: ["pendampingan-komunitas", "pemberdayaan-perempuan", "pengelolaan-sampah-organik"],
        featured: true,
        narrative:
          "Program kerja sama dengan Pertamina Geothermal Energy Lahendong mencakup edukasi pemilahan sampah plastik dan pelatihan eco-enzyme. Program Bank Sampah Setor Jo di Desa Pinabetengan Utara dan pengembangan produk daur ulang.",
        highlights: [
          "Bank Sampah Setor Jo di Desa Pinabetengan Utara",
          "Produk daur ulang: sofa ecobrick, gantungan kunci, tas",
          "Pelatihan eco-enzyme untuk perempuan",
          "Sabun, detergen, dan pupuk organik dari limbah organik",
        ],
        photos: [
          { src: "/2022/20221013_100454.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/20221014_113726.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/20221020_101816.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1641858263983.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642078941101.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642078944320.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642080513657.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642080516908.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642080519457.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642080521919.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642080524132.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642080526366.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642080528610.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642080531835.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642080534411.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642080543726.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1642080549112.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1644307803313.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1644552128352.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1644633312960.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1644633315829.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1644633340204.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1644911548955.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1648297578960.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1648347257598.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1648687513379.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1648687518640.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1648687561021.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1649129397700.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1649762676520.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1653799265424.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1656122103483.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1657255521078.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1660095100171.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1660352827145.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1662204980176.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1662204998683.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1662806996913.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1662807011093.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1662807020970.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1662807060862.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1663415955314.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1664088683251.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/FB_IMG_1673331471290.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220106_172355.webp", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220106_182443.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220113_124550.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220127_174227.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220131_165406.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220131_165408.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220131_165437.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220206_182604.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220211_122039.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220211_122043.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220306_150042.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220329_002254.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220403_174205.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220407_134017.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220407_134028.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220407_141106.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220407_142447.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220426_100300.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220428_191423.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220430_094734.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220505_182015.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220505_182415.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220515_171115.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220528_151012.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220528_151022.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220528_151758.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220605_173619.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220611_144302.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220614_192627.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220622_201528.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220625_170624.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220627_142905.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220630_164937.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220702_130554.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220705_214653.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220808_154413.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220810_162202.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220812_183357.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220813_130549.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220825_135845.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220826_150843.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220828_205813.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220904_154707.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220904_172326.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220904_194722.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220904_230402.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220908_182604.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220910_114915.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220910_144655.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220912_135428.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20220916_102920.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20221010_180706.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20221011_112014.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20221013_174613.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20221013_180031.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20221014_113854.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20221016_104504.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20221022_161151.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20221022_161207.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20221103_140404.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20221228_112353.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20221229_154627.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20221229_171152.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20230104_141447.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/IMG_20230105_165010.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/Screenshot_2022-01-06-17-24-06-117_us.zoom.videomeetings.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/Screenshot_2022-03-02-17-48-08-025_us.zoom.videomeetings.jpg", alt: "Kegiatan 2022" },
          { src: "/2022/Screenshot_2022-04-03-10-36-39-969_com.android.chrome.jpg", alt: "Kegiatan 2022" },
        ],
      },
    ],
  },
  {
    year: 2023,
    activities: [
      {
        id: "bijak-berplastik-danone",
        title: "Program Bijak Berplastik Danone Aqua",
        titleKey: "trackRecordData.activity.41.title",
        narrativeKey: "trackRecordData.activity.41.narrative",
        location: "Likupang",
        role: "Mitra Pelaksana",
        era: "transformasi",
        categories: ["lingkungan", "ekonomi"],
        capabilities: ["pengelolaan-sampah-wisata"],
        narrative:
          "Kerja sama Danone Aqua dengan Baciraro Recycle untuk fasilitas penampungan sampah plastik, didukung Komunitas Pecinta Alam Likupang. Penguatan ekosistem pengelolaan sampah DPSP Likupang.",
        highlights: [
          "Fasilitas penampungan sampah plastik",
          "Bank Sampah Induk Likupang di Desa Serawet",
          "Kegiatan bersih-bersih pantai dan kampung",
          "Alur terintegrasi ke ekosistem pengelolaan sampah",
        ],
        photos: [
          { src: "/2023/FB_IMG_1676076333322.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/IMG20230510091609.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/IMG_20230121_213236.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/IMG_20230121_213314.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/IMG_20230121_213323.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/IMG_20230121_213331.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/IMG_20230121_213341.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/IMG_20230121_213349.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/IMG_20230208_110944.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/IMG_20230316_223413.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/IMG_20230321_190018.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/IMG_20230328_110320.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/IMG_20230404_142636.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/Screenshot_2023-01-31-16-05-45-947_us.zoom.videomeetings.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/Screenshot_2023-02-10-19-49-22-370_us.zoom.videomeetings.jpg", alt: "Kegiatan 2023" },
          { src: "/2023/Screenshot_2023-02-10-20-29-54-746_us.zoom.videomeetings.jpg", alt: "Kegiatan 2023" },
        ],
      },
    ],
  },
  {
    year: 2024,
    activities: [
      {
        id: "desa-pesisir-bumn",
        title: "Program Desa Pesisir & Kolaborasi BUMN",
        titleKey: "trackRecordData.activity.42.title",
        narrativeKey: "trackRecordData.activity.42.narrative",
        location: "Likupang",
        role: "Eksekutor",
        era: "transformasi",
        categories: ["lingkungan", "sosial", "ekonomi"],
        capabilities: ["pengelolaan-sampah-pesisir", "pendampingan-komunitas"],
        featured: true,
        narrative:
          "Kolaborasi dengan Kementerian Kelautan, Perikanan, dan Kementerian Pariwisata untuk pemberdayaan nelayan dan desa wisata. Program Desa Pesisir Bersih di Desa Serawet dan pelatihan Manajemen Bank Sampah.",
        highlights: [
          "Program Desa Pesisir Bersih di Desa Serawet",
          "Pemberdayaan nelayan dan pengelolaan sampah terpilah",
          "Pelatihan Manajemen Bank Sampah (25 peserta, 5 desa wisata)",
          "Kolaborasi BUMN melalui program TJSL/CSR",
          "Dukungan ekonomi kreatif di destinasi wisata",
        ],
        photos: [
          { src: "/2024/IMG20240409232612.jpg", alt: "Kegiatan 2024" },
          { src: "/2024/IMG20240413085650.jpg", alt: "Kegiatan 2024" },
          { src: "/2024/IMG20240428191222.jpg", alt: "Kegiatan 2024" },
          { src: "/2024/IMG20240510100400.jpg", alt: "Kegiatan 2024" },
          { src: "/2024/IMG20240510100826.jpg", alt: "Kegiatan 2024" },
        ],
      },
    ],
  },
  {
    year: 2026,
    activities: [
      {
        id: "dialog-budaya-minahasa-2026",
        title: "Dialog Budaya Minahasa 2026",
        titleKey: "trackRecordData.activity.43.title",
        narrativeKey: "trackRecordData.activity.43.narrative",
        location: "Minahasa Utara",
        role: "Penyelenggara",
        era: "transformasi",
        categories: ["lingkungan", "sosial"],
        featured: true,
        narrative:
          "Forum dialog yang menelusuri evolusi atribut Kawasaran — mengurai benang merah antara otentisitas budaya dan inovasi plastik daur ulang. Mempertemukan tokoh adat, akademisi, seniman, pegiat lingkungan, pemerintah, dan generasi muda di Kedai Kana, Desa Sukur, Minahasa Utara.",
        highlights: [
          "Dialog lintas perspektif: adat, sejarah, akademik, seni, dan lingkungan",
          "Penelusuran evolusi atribut Kawasaran dan inovasi plastik daur ulang",
          "Penandatanganan deklarasi dan rekomendasi awal tindak lanjut",
        ],
        photos: [
          { src: "/Dialog Budaya/registrasi.jpeg", alt: "Registrasi Dialog Budaya" },
          { src: "/Dialog Budaya/foto bersama dengan narasumber.webp", alt: "Foto bersama dengan narasumber" },
          { src: "/Dialog Budaya/foto bersama dengan narasumber 2.webp", alt: "Foto bersama dengan narasumber" },
          { src: "/Dialog Budaya/foto bersama dengan narasumber 3.webp", alt: "Foto bersama dengan narasumber" },
          { src: "/Dialog Budaya/foto bersama dengan narasumber 4.webp", alt: "Foto bersama dengan narasumber" },
          { src: "/Dialog Budaya/foto bersama dengan narasumber 5.webp", alt: "Foto bersama dengan narasumber" },
          { src: "/Dialog Budaya/foto bersama dengan narasumber 6.webp", alt: "Foto bersama dengan narasumber" },
          { src: "/Dialog Budaya/foto bersama dengan narasumber dan tamu undangan2.jpeg", alt: "Foto bersama narasumber dan tamu undangan" },
          { src: "/Dialog Budaya/foto bersama dengan narasumber dan tamu undangan 3.jpeg", alt: "Foto bersama narasumber dan tamu undangan" },
          { src: "/Dialog Budaya/foto bersama dengan narasumber dan tamu undangan 4.jpeg", alt: "Foto bersama narasumber dan tamu undangan" },
          { src: "/Dialog Budaya/foto bersama dengan narasumber dan tamu undangan 5.jpeg", alt: "Foto bersama narasumber dan tamu undangan" },
          { src: "/Dialog Budaya/foto bersama dengan narasumber dan tamu undangan 6.jpeg", alt: "Foto bersama narasumber dan tamu undangan" },
          { src: "/Dialog Budaya/foto bersama panitia.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 2.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 3.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 4.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 5.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 6.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 7.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 8.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 9.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 10.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 11.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 12.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 13.webp", alt: "Foto bersama panitia" },
          { src: "/Dialog Budaya/foto bersama panitia 14.webp", alt: "Foto bersama panitia" },
        ],
      },
      {
        id: "lokawaya-baciraro-creative",
        title: "Lokawaya × Baciraro Creative",
        titleKey: "trackRecordData.activity.44.title",
        narrativeKey: "trackRecordData.activity.44.narrative",
        location: "Minahasa Utara",
        role: "Peserta",
        era: "transformasi",
        categories: ["lingkungan", "ekonomi"],
        narrative:
          "Partisipasi Baciraro Creative di event Lokawaya — workshop mengubah tutup botol menjadi keychain dan booth produk yang dapat ditukar dengan Dobu atau Doi Bulu. Dikunjungi turis asing dan lokal yang antusias berinteraksi dengan produk daur ulang.",
        highlights: [
          "Workshop tutup botol jadi keychain",
          "Booth produk yang dapat ditukar dengan Dobu atau Doi Bulu",
          "Kunjungan turis asing dan lokal",
        ],
        photos: [
          { src: "/Lokawaya/customer anak dari USA setelah selesai membuat sendiri keychainnya dari tutup botol plastik.jpeg", alt: "Anak dari USA selesai membuat keychain" },
          { src: "/Lokawaya/kondisi booth baciraro creative.png", alt: "Kondisi booth Baciraro Creative" },
          { src: "/Lokawaya/kondisi lokawaya.png", alt: "Kondisi Lokawaya" },
          { src: "/Lokawaya/kondisi lokawaya 2.png", alt: "Kondisi Lokawaya" },
          { src: "/Lokawaya/kondisi workshop baciraro creative.png", alt: "Kondisi workshop Baciraro Creative" },
          { src: "/Lokawaya/kunjungan dari turis asing.png", alt: "Kunjungan turis asing" },
          { src: "/Lokawaya/kunjungan dari turis asing 2.png", alt: "Kunjungan turis asing" },
          { src: "/Lokawaya/kunjungan dari turis asing 3.png", alt: "Kunjungan turis asing" },
          { src: "/Lokawaya/kunjungan dari turis asing 4.png", alt: "Kunjungan turis asing" },
          { src: "/Lokawaya/kunjungan dari turis asing 5.png", alt: "Kunjungan turis asing" },
          { src: "/Lokawaya/kunjungan dari turis asing 6.png", alt: "Kunjungan turis asing" },
          { src: "/Lokawaya/kunjungan dari turis lokal dan asing.png", alt: "Kunjungan turis lokal dan asing" },
          { src: "/Lokawaya/kunjungan turis dari USA.png", alt: "Kunjungan turis dari USA" },
          { src: "/Lokawaya/proses pembuatan keychain anak dari USA.png", alt: "Proses pembuatan keychain anak dari USA" },
          { src: "/Lokawaya/timelapse booth.png", alt: "Timelapse booth" },
          { src: "/Lokawaya/timelapse workshop.png", alt: "Timelapse workshop" },
          { src: "/Lokawaya/video produk.png", alt: "Video produk" },
        ],
      },
    ],
  },
];
