-- MakerWorld batch 3 (produk murah/ringan) - integrated products
-- Run in Supabase SQL Editor. Replaces/updates rows by id.
INSERT INTO products (id, slug, title, description, category, story, materials, total_plastic_kg, image_url, gallery, is_active, weight_g, print_time_min, variants, artists) VALUES
(900010, '3d-mini-shark', 'Mini Shark Articulated', 'Hiu mini artikulasi yang lentur, cocok untuk gantungan kunci maupun mainan meja. Cetak cepat, hanya sekitar 20 menit.', '3dprint', 'Hiu kecil dengan badan artikulasi yang bisa digoyang-goyang. Ukurannya pas untuk gantungan kunci dan hadiah, serta sangat cepat dicetak sehingga murah.', '[]', 0, '/produk/3d/batch3/3d-mini-shark-1.jpg', '["/produk/3d/batch3/3d-mini-shark-2.jpg"]', true, 12, 23, '[{"label":"Single color","weight_g":12,"minutes":23},{"label":"Multicolor","weight_g":45,"minutes":66},{"label":"Mass production (reduced time)","weight_g":11,"minutes":20}]', '[]'),
(900011, '3d-whale-shark-keychain', 'Whale Shark Articulated Keychain', 'Hiu paus artikulasi versi mini dengan lubang gantungan kunci. Ringan, imut, dan bisa meliuk seperti berenang.', '3dprint', 'Hiu paus yang ramah, dibuat dalam ukuran miniaturnya lengkap dengan gantungan. Segmen artikulasinya bergerak bebas, pas untuk aksesori harian atau hadiah tema laut.', '[]', 0, '/produk/3d/batch3/3d-whale-shark-keychain-1.jpg', '["/produk/3d/batch3/3d-whale-shark-keychain-2.jpg", "/produk/3d/batch3/3d-whale-shark-keychain-3.jpg"]', true, 16, 31, '[{"label":"Strong 0.20mm","weight_g":16,"minutes":31},{"label":"Multicolor","weight_g":30,"minutes":78}]', '[]'),
(900012, '3d-articulated-caterpillar', 'Articulated Caterpillar', 'Ulat artikulasi print-in-place tanpa support. Mudah dicetak, seru dimainkan, dan bisa untuk hadiah anak maupun giveaway.', '3dprint', 'Ulat dengan segmen-segmen lentur yang mencetak dalam sekali jalan tanpa perakitan. Motif gerakannya yang mengalir membuatnya menyenangkan untuk anak-anak.', '[]', 0, '/produk/3d/batch3/3d-articulated-caterpillar-1.webp', '["/produk/3d/batch3/3d-articulated-caterpillar-2.png"]', true, 15, 58, '[{"label":"Standar 8 segmen","weight_g":15,"minutes":58},{"label":"Panjang 12 segmen","weight_g":25,"minutes":102}]', '[]'),
(900013, '3d-articulated-octopus', 'Articulated Octopus', 'Gurita artikulasi dengan lengan yang lentur. Print-in-place, tanpa support, langsung main begitu keluar dari printer.', '3dprint', 'Gurita yang seluruh lengannya bisa digerakkan, dirancang agar mudah dicetak dan menyenangkan untuk dimainkan. Cocok untuk desk toy, mainan anak, dan hadiah.', '[]', 0, '/produk/3d/batch3/3d-articulated-octopus-1.png', '["/produk/3d/batch3/3d-articulated-octopus-2.png", "/produk/3d/batch3/3d-articulated-octopus-3.png", "/produk/3d/batch3/3d-articulated-octopus-4.png"]', true, 22, 66, '[{"label":"Standar 0.16mm","weight_g":22,"minutes":66},{"label":"Colored Eyes (AMS)","weight_g":26,"minutes":102}]', '[]'),
(900014, '3d-turtle-25pcs', 'Set 25 Mini Turtles', 'Paket 25 penyu mini dalam satu cetakan. Hemat biaya per pcs, pas untuk suvenir, hadiah ulang tahun, dan event.', '3dprint', 'Dua puluh lima penyu kecil yang dicetak sekaligus. Setiap penyu ringan sehingga murah per buah, cocok untuk didistribusikan sebagai suvenir atau ditempatkan di toko.', '[]', 0, '/produk/3d/batch3/3d-turtle-25pcs-1.jpg', '["/produk/3d/batch3/3d-turtle-25pcs-2.jpg"]', true, 130, 474, '[{"label":"25 pcs (1 cetakan)","weight_g":130,"minutes":474},{"label":"15 pcs (A1 mini)","weight_g":80,"minutes":306}]', '[]'),
(900015, '3d-amazing-star-fidget', 'Amazing Star Fidget', 'Fidget bintang yang bisa diputar dan mengembang-merapat. Sensasi kinetik yang menghipnotis, tanpa perakitan.', '3dprint', 'Bintang mekanik berputar yang membuka dan menutup dengan gerakan memuaskan. Silky PLA membuat gerakannya mulus dan tampilannya berkilau.', '[]', 0, '/produk/3d/batch3/3d-amazing-star-fidget-1.png', '["/produk/3d/batch3/3d-amazing-star-fidget-2.jpg"]', true, 40, 132, '[{"label":"Mini (2.2 jam)","weight_g":40,"minutes":132},{"label":"Full 100% (7 in)","weight_g":160,"minutes":384}]', '[]')
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, description = EXCLUDED.description, category = EXCLUDED.category, story = EXCLUDED.story, image_url = EXCLUDED.image_url, gallery = EXCLUDED.gallery, is_active = true, weight_g = EXCLUDED.weight_g, print_time_min = EXCLUDED.print_time_min, variants = EXCLUDED.variants, artists = EXCLUDED.artists;