-- MakerWorld batch 2 (sea/satwa/religi/nama) - integrated products
-- Run in Supabase SQL Editor. Replaces/updates rows by slug.
INSERT INTO products (slug, title, description, category, story, materials, total_plastic_kg, image_url, gallery, is_active, weight_g, print_time_min, variants, artists) VALUES
('3d-whale-shark', 'Articulated Whale Shark', 'Hiu paus artikulasi dengan 7 segmen yang lentur dan bisa digerakkan bebas. Cetak langsung jadi satu, tanpa perakitan.', '3dprint', 'Hiu paus yang hidup, dibentuk dari segmen-segmen artikulasi yang saling terhubung. Begitu keluar dari printer, modelnya bisa meliuk seperti berenang. Pilihan tepat untuk koleksi tema laut dan hadiah edukatif.', '[]', 0, '/produk/3d/mw-b2/3d-whale-shark-1.png', '["/produk/3d/mw-b2/3d-whale-shark-2.png", "/produk/3d/mw-b2/3d-whale-shark-3.jpeg"]', true, 60, 150, '[{"label":"Standar","weight_g":60,"minutes":150}]', '[]'),
('3d-starfish', 'Starfish Flexi', 'Bintang laut fleksibel yang bisa digoyangkan lengannya. Satu cetakan utuh, langsung main tanpa perakitan.', '3dprint', 'Bintang laut dengan lengan fleksibel yang dapat digerakkan ke segala arah. Desain print-in-place membuatnya keluar dari printer dalam kondisi siap main. Pas untuk hadiah, dekorasi meja, dan tema konservasi laut.', '[]', 0, '/produk/3d/mw-b2/3d-starfish-1.jpg', '["/produk/3d/mw-b2/3d-starfish-2.jpg", "/produk/3d/mw-b2/3d-starfish-3.jpg", "/produk/3d/mw-b2/3d-starfish-4.jpg"]', true, 25, 80, '[{"label":"Standar","weight_g":25,"minutes":80}]', '[]'),
('3d-orca-whale', 'Flexi Orca Whale', 'Orca atau paus pembunuh dengan badan fleksibel yang mengalir. Cetak satu warna atau warna-warni.', '3dprint', 'Orca dengan tubuh ramping dan sirip yang khas, dirancang agar bisa digoyangkan dari ekor hingga kepala. Menjadi koleksi lautan yang menarik sekaligus mainan yang menyenangkan.', '[]', 0, '/produk/3d/mw-b2/3d-orca-whale-1.jpg', '["/produk/3d/mw-b2/3d-orca-whale-2.jpg", "/produk/3d/mw-b2/3d-orca-whale-3.jpg", "/produk/3d/mw-b2/3d-orca-whale-4.jpg"]', true, 40, 120, '[{"label":"Standar","weight_g":40,"minutes":120}]', '[]'),
('3d-flexi-shark', 'Flexi Baby Shark Keychain', 'Hiu kecil fleksibel plus varian gantungan kunci. Imut, ringan, dan siap menemani kunci harianmu.', '3dprint', 'Bayi hiu dengan badan fleksibel yang menggemaskan, tersedia versi gantungan kunci untuk aksesori harian. Profil cetak cepat dengan hasil rapi.', '[]', 0, '/produk/3d/mw-b2/3d-flexi-shark-1.jpg', '["/produk/3d/mw-b2/3d-flexi-shark-3.jpg", "/produk/3d/mw-b2/3d-flexi-shark-4.jpg"]', true, 12, 45, '[{"label":"Standar","weight_g":12,"minutes":45}]', '[]'),
('3d-jellyfish-fidget', 'Articulated Jellyfish Fidget', 'Ubur-ubur fidget dengan 16 tentakel fleksibel. Menghipnotis saat diputar dan diletakkan.', '3dprint', 'Ubur-ubur dengan enam belas tentakel yang lentur, menyenangkan untuk dipelintir dan diputar sebagai pelepas stres. Bentuknya yang mengambang memberi efek menenangkan di meja kerja.', '[]', 0, '/produk/3d/mw-b2/3d-jellyfish-fidget-1.jpg', '["/produk/3d/mw-b2/3d-jellyfish-fidget-2.jpg", "/produk/3d/mw-b2/3d-jellyfish-fidget-3.jpg", "/produk/3d/mw-b2/3d-jellyfish-fidget-4.jpg"]', true, 18, 60, '[{"label":"Standar","weight_g":18,"minutes":60}]', '[]'),
('3d-hammerhead-shark', 'Mini Articulated Hammerhead Shark', 'Hiu martil mini yang lentur dengan kepala khas. Ringan dan mudah dimainkan atau dijadikan koleksi.', '3dprint', 'Hiu martil dalam versi mini yang tetap detail. Badan artikulasi bergerak mengikuti goyangan, cocok untuk koleksi satwa laut dan mainan edukatif.', '[]', 0, '/produk/3d/mw-b2/3d-hammerhead-shark-1.png', '["/produk/3d/mw-b2/3d-hammerhead-shark-2.png", "/produk/3d/mw-b2/3d-hammerhead-shark-3.png", "/produk/3d/mw-b2/3d-hammerhead-shark-4.png"]', true, 15, 55, '[{"label":"Standar","weight_g":15,"minutes":55}]', '[]'),
('3d-flexi-seal', 'Cute Flexi Seal', 'Anjing laut fleksibel yang menggemaskan, siap digoyang-goyang. Pilihan hadiah yang menyenangkan.', '3dprint', 'Anjing laut lucu dengan tubuh artikulasi yang lentur. Bentuknya yang ramah cocok untuk mainan anak maupun pajangan meja dengan sentuhan tema lautan.', '[]', 0, '/produk/3d/mw-b2/3d-flexi-seal-1.jpg', '["/produk/3d/mw-b2/3d-flexi-seal-2.jpg", "/produk/3d/mw-b2/3d-flexi-seal-3.jpg", "/produk/3d/mw-b2/3d-flexi-seal-4.jpg"]', true, 30, 90, '[{"label":"Standar","weight_g":30,"minutes":90}]', '[]'),
('3d-flexi-turtle', 'Flexible Articulated Turtle', 'Penyu artikulasi dengan kaki dan kepala yang bisa digerakkan. Cetak dalam sekali jalan, tanpa perakitan.', '3dprint', 'Penyu dengan anggota tubuh fleksibel yang merekah hidup begitu digoyang. Desain print-in-place dengan detail tempurung yang rapi, melengkapi tema konservasi penyu.', '[]', 0, '/produk/3d/mw-b2/3d-flexi-turtle-1.jpg', '["/produk/3d/mw-b2/3d-flexi-turtle-2.jpg", "/produk/3d/mw-b2/3d-flexi-turtle-3.jpg", "/produk/3d/mw-b2/3d-flexi-turtle-4.jpg"]', true, 28, 85, '[{"label":"Standar","weight_g":28,"minutes":85}]', '[]'),
('3d-flexi-dolphin', 'Flexi Dolphin', 'Lumba-lumba fleksibel yang lincah, lengkap dengan gerakan menyelam yang alami.', '3dprint', 'Lumba-lumba dengan tubuh lentur yang mengikuti gerakan tangan. Bentuk dinamisnya cocok untuk kolektor fauna laut maupun hadiah yang penuh semangat.', '[]', 0, '/produk/3d/mw-b2/3d-flexi-dolphin-1.jpg', '["/produk/3d/mw-b2/3d-flexi-dolphin-2.jpg"]', true, 22, 70, '[{"label":"Standar","weight_g":22,"minutes":70}]', '[]'),
('3d-flexi-owl', 'Flexi Baby Owl Keychain', 'Burung hantu kecil fleksibel plus varian gantungan kunci. Bentuk manguni yang ikonik dalam versi lucu.', '3dprint', 'Burung hantu bayi yang lembut dan lentur, terinspirasi dari sosok manguni yang ikonik. Varian gantungan kunci membuatnya praktis dibawa ke mana pun.', '[]', 0, '/produk/3d/mw-b2/3d-flexi-owl-1.jpg', '["/produk/3d/mw-b2/3d-flexi-owl-2.jpg", "/produk/3d/mw-b2/3d-flexi-owl-3.jpg", "/produk/3d/mw-b2/3d-flexi-owl-4.jpg"]', true, 10, 40, '[{"label":"Standar","weight_g":10,"minutes":40}]', '[]'),
('3d-articulated-corgi', 'Articulated Corgi', 'Corgi artikulasi yang menggemaskan dengan gerakan badan yang lentur. Koleksi satwa yang hangat.', '3dprint', 'Corgi dengan telinga khas dan tubuh artikulasi yang bisa digoyang-goyang. Menghadirkan keceriaan di meja kerja atau rak koleksi.', '[]', 0, '/produk/3d/mw-b2/3d-articulated-corgi-1.jpg', '["/produk/3d/mw-b2/3d-articulated-corgi-2.jpg", "/produk/3d/mw-b2/3d-articulated-corgi-3.jpg", "/produk/3d/mw-b2/3d-articulated-corgi-4.jpg"]', true, 35, 100, '[{"label":"Standar","weight_g":35,"minutes":100}]', '[]'),
('3d-nativity-3kings', 'Nativity Scene with 3 Kings', 'Adegan Natal lengkap: palungan, bayi Yesus, Maria, tiga raja, domba, dan bintang terang. Cocok untuk dekorasi hari raya.', '3dprint', 'Set Natal klasik dengan palungan, bayi Yesus, Maria, tiga raja, domba, keledai, dan bintang. Menjadi dekorasi Natal yang bermakna untuk rumah maupun gereja.', '[]', 0, '/produk/3d/mw-b2/3d-nativity-3kings-1.jpeg', '[]', true, 120, 300, '[{"label":"Standar","weight_g":120,"minutes":300}]', '[]'),
('3d-nativity-illuminated', 'Illuminated Nativity Scene', 'Adegan Keluarga Kudus di bawah sayap malaikat yang bisa diberi cahaya LED atau lampu teh. Dekorasi Natal yang hangat.', '3dprint', 'Nativity dengan sayap malaikat besar yang melindungi Keluarga Kudus. Dapat diterangi lampu teh atau kit LED sehingga menjadi lampu Natal yang menyentuh.', '[]', 0, '/produk/3d/mw-b2/3d-nativity-illuminated-1.jpg', '["/produk/3d/mw-b2/3d-nativity-illuminated-2.jpg", "/produk/3d/mw-b2/3d-nativity-illuminated-3.jpg", "/produk/3d/mw-b2/3d-nativity-illuminated-4.jpg"]', true, 90, 250, '[{"label":"Standar","weight_g":90,"minutes":250}]', '[]'),
('3d-name-keychain', 'Custom Name Keychain', 'Gantungan kunci nama yang bisa disesuaikan. Pilih nama, font, dan warna untuk hadiah personal.', '3dprint', 'Gantungan nama dengan parameter yang bisa diatur langsung: teks, font, dan warna. Siap dicetak dalam sekejap untuk hadiah, merchandise, maupun kebutuhan branding.', '[]', 0, '/produk/3d/mw-b2/3d-name-keychain-1.png', '["/produk/3d/mw-b2/3d-name-keychain-2.png", "/produk/3d/mw-b2/3d-name-keychain-3.png"]', true, 5, 20, '[{"label":"Standar","weight_g":5,"minutes":20}]', '[]'),
('3d-name-tag', 'Name Tag Keychain', 'Name tag keychain dengan koleksi 1.200 nama siap cetak. Ringan, cepat, dan pas untuk hadiah serta event.', '3dprint', 'Label nama gantungan kunci dengan ribuan pilihan nama yang siap cetak dalam hitungan menit. Praktis untuk suvenir, acara, dan hadiah personal.', '[]', 0, '/produk/3d/mw-b2/3d-name-tag-1.webp', '["/produk/3d/mw-b2/3d-name-tag-2.webp", "/produk/3d/mw-b2/3d-name-tag-3.webp", "/produk/3d/mw-b2/3d-name-tag-4.webp"]', true, 4, 15, '[{"label":"Standar","weight_g":4,"minutes":15}]', '[]')
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, category = EXCLUDED.category, story = EXCLUDED.story, image_url = EXCLUDED.image_url, gallery = EXCLUDED.gallery, is_active = true, weight_g = EXCLUDED.weight_g, print_time_min = EXCLUDED.print_time_min, variants = EXCLUDED.variants, artists = EXCLUDED.artists;
