-- MakerWorld batch 4 (flexi, lisensi diabaikan) - integrated products
-- Run in Supabase SQL Editor. Replaces/updates rows by id.
INSERT INTO products (id, slug, title, description, category, story, materials, total_plastic_kg, image_url, gallery, is_active, weight_g, print_time_min, variants, artists) VALUES
(900020, '3d-flexi-axolotl', 'Flexi Axolotl Articulated', 'Axolotl artikulasi print-in-place yang lentur dan imut. Tanpa support, langsung bisa dimainkan begitu keluar dari printer.', '3dprint', 'Axolotl dengan badan bersegmen yang bisa digoyang-goyang. Cetak sekali jalan tanpa perakitan, cocok untuk mainan meja, hadiah anak, dan teman fidget harian.', '[]', 0, '/produk/3d/batch4/3d-flexi-axolotl-1.jpg', '["/produk/3d/batch4/3d-flexi-axolotl-2.jpg"]', true, 37, 118, '[{"label":"Standar","weight_g":37,"minutes":118},{"label":"Multicolor","weight_g":70,"minutes":177}]', '[]'),
(900021, '3d-axolotl-fidget', 'Axolotl Fidget Articulated', 'Fidget axolotl artikulasi yang lucu dan bisa digerak-gerakkan. Ringan, tanpa support, siap main langsung setelah dicetak.', '3dprint', 'Versi fidget dari axolotl dengan tubuh yang lentur. Menghibur di meja kerja dan mudah dicetak, jadi kandidat bagus untuk suvenir dan hadiah kecil.', '[]', 0, '/produk/3d/batch4/3d-axolotl-fidget-1.jpg', '["/produk/3d/batch4/3d-axolotl-fidget-2.jpg"]', true, 44, 141, '[{"label":"Standar","weight_g":44,"minutes":141},{"label":"Multicolor","weight_g":84,"minutes":212}]', '[]'),
(900022, '3d-flexi-manta-ray', 'Flexi Manta Ray', 'Manta ray artikulasi dengan sayap dan tubuh yang bergerak fleksibel. Print-in-place, detail, dan sangat memuaskan untuk dimainkan.', '3dprint', 'Seluruh tubuh manta ray tersambung engsel sehingga bisa meliuk seperti berenang. Desain klasik yang populer untuk koleksi satwa laut yang lentur.', '[]', 0, '/produk/3d/batch4/3d-flexi-manta-ray-1.jpg', '["/produk/3d/batch4/3d-flexi-manta-ray-2.jpg"]', true, 138, 441, '[{"label":"Standar","weight_g":138,"minutes":441},{"label":"Multicolor","weight_g":262,"minutes":662}]', '[]'),
(900023, '3d-mini-turtle', 'Mini Turtle Articulated', 'Penyu mini artikulasi yang cepat dicetak (sekitar 27 menit). Kecil, imut, dan murah — pas untuk suvenir dan hadiah.', '3dprint', 'Penyu mungil dengan leher dan kaki yang bisa bergerak. Waktu cetak super cepat membuatnya ideal untuk produksi massal kecil dan suvenir acara.', '[]', 0, '/produk/3d/batch4/3d-mini-turtle-1.jpg', '["/produk/3d/batch4/3d-mini-turtle-2.jpg"]', true, 81, 259, '[{"label":"Standar","weight_g":81,"minutes":259},{"label":"Multicolor","weight_g":154,"minutes":388}]', '[]'),
(900024, '3d-zookis-chameleon', 'Zookis Chameleon', 'Bunglon mini dari seri Zookis yang lentur dan cepat dicetak. Cocok untuk suvenir, hadiah, dan koleksi satwa mini.', '3dprint', 'Bunglon mungil dengan ekor dan tubuh yang bisa digoyang. Ukuran mini dan cetak cepat membuatnya murah per buah, cocok dijual sebagai gantungan maupun suvenir.', '[]', 0, '/produk/3d/batch4/3d-zookis-chameleon-1.jpg', '["/produk/3d/batch4/3d-zookis-chameleon-2.jpg"]', true, 7, 21, '[{"label":"Standar","weight_g":7,"minutes":21},{"label":"Multicolor","weight_g":13,"minutes":32}]', '[]'),
(900025, '3d-zookis-crocodile', 'Zookis Crocodile', 'Buaya mini dari seri Zookis dengan rahang dan badan lentur. Imut, ringan, dan cepat dicetak.', '3dprint', 'Buaya kecil yang menggemaskan dengan tubuh bersegmen. Desain mini yang ekonomis untuk suvenir tema satwa dan hadiah anak.', '[]', 0, '/produk/3d/batch4/3d-zookis-crocodile-1.jpg', '["/produk/3d/batch4/3d-zookis-crocodile-2.jpg"]', true, 6, 20, '[{"label":"Standar","weight_g":6,"minutes":20},{"label":"Multicolor","weight_g":11,"minutes":30}]', '[]'),
(900026, '3d-spike-dragon', 'Articulated Spike Dragon', 'Naga berduri artikulasi yang gagah. Print-in-place tanpa support, badan bersegmen yang bergerak bebas.', '3dprint', 'Naga dengan deretan duri di punggung dan tubuh yang lentur. Penampilannya dramatis namun mudah dicetak, seru untuk koleksi dan mainan meja.', '[]', 0, '/produk/3d/batch4/3d-spike-dragon-1.jpg', '["/produk/3d/batch4/3d-spike-dragon-2.jpg"]', true, 42, 133, '[{"label":"Standar","weight_g":42,"minutes":133},{"label":"Multicolor","weight_g":80,"minutes":200}]', '[]'),
(900027, '3d-flexi-dragon', 'Flexi Dragon Articulated', 'Naga artikulasi print-in-place yang mulus bergerak. Tersedia versi satu warna dan multicolor, tanpa support.', '3dprint', 'Naga dengan tubuh bersegmen yang dirancang agar bisa langsung bergerak dari print bed. Bisa untuk display, desk toy, atau koleksi.', '[]', 0, '/produk/3d/batch4/3d-flexi-dragon-1.jpg', '["/produk/3d/batch4/3d-flexi-dragon-2.jpg"]', true, 62, 199, '[{"label":"Standar","weight_g":62,"minutes":199},{"label":"Multicolor","weight_g":118,"minutes":298}]', '[]'),
(900028, '3d-flexi-toothless', 'Flexi Toothless Dragon', 'Naga Toothless flexi yang bisa berdiri, duduk, dan mengepakkan sayap. Multicolor, tanpa support.', '3dprint', 'Reproduksi naga mungil yang ikonik dengan sayap yang bisa dikepakkan. Salah satu model flexi paling populer, menyenangkan untuk penggemar dan kolektor.', '[]', 0, '/produk/3d/batch4/3d-flexi-toothless-1.jpg', '["/produk/3d/batch4/3d-flexi-toothless-2.jpg"]', true, 102, 327, '[{"label":"Standar","weight_g":102,"minutes":327},{"label":"Multicolor","weight_g":194,"minutes":490}]', '[]'),
(900029, '3d-flexi-bearded-dragon', 'Flexi Bearded Dragon', 'Biawak berjanggut flexi realistis dengan hampir semua sisik yang lentur. Print-in-place, tanpa brim dan support.', '3dprint', 'Reptil peliharaan dalam bentuk flexi yang detail dan sangat lentur. Desainnya yang hidup membuatnya cocok untuk penggemar reptil dan koleksi satwa.', '[]', 0, '/produk/3d/batch4/3d-flexi-bearded-dragon-1.jpg', '["/produk/3d/batch4/3d-flexi-bearded-dragon-2.jpg"]', true, 118, 378, '[{"label":"Standar","weight_g":118,"minutes":378},{"label":"Multicolor","weight_g":224,"minutes":567}]', '[]'),
(900030, '3d-flexi-pangolin', 'Flexi Pangolin', 'Pangolin flexi super detail dengan hampir seluruh sisiknya lentur. Print-in-place, tanpa support, sangat memuaskan.', '3dprint', 'Tenggiling dengan sisik-sisik individual yang bisa bergerak satu per satu. Salah satu model flexi paling detail dan menakjubkan untuk pengoleksi.', '[]', 0, '/produk/3d/batch4/3d-flexi-pangolin-1.jpg', '["/produk/3d/batch4/3d-flexi-pangolin-2.jpg"]', true, 228, 600, '[{"label":"Standar","weight_g":228,"minutes":600},{"label":"Multicolor","weight_g":433,"minutes":900}]', '[]'),
(900031, '3d-flexi-scorpion', 'Flexi Scorpion', 'Kalajengking artikulasi dengan capit dan ekor yang bergerak lentur. Cetak sekali jalan, tanpa support.', '3dprint', 'Kalajengking dengan kaki, capit, dan ekor bersegmen yang bisa digerakkan. Koleksi satwa unik yang seru dan mudah dicetak.', '[]', 0, '/produk/3d/batch4/3d-flexi-scorpion-1.jpg', '["/produk/3d/batch4/3d-flexi-scorpion-2.jpg"]', true, 145, 463, '[{"label":"Standar","weight_g":145,"minutes":463},{"label":"Multicolor","weight_g":276,"minutes":694}]', '[]'),
(900032, '3d-flexi-manta-ray-pip', 'Flexi Manta Ray Print-in-Place', 'Manta ray print-in-place tanpa support dengan sayap yang bergerak mulus. Desain ringkas dan mudah dicetak.', '3dprint', 'Versi print-in-place dari manta ray yang dioptimalkan tanpa support. Sayap dan tubuhnya bergerak alami seperti berenang di laut.', '[]', 0, '/produk/3d/batch4/3d-flexi-manta-ray-pip-1.jpg', '["/produk/3d/batch4/3d-flexi-manta-ray-pip-2.jpg"]', true, 118, 379, '[{"label":"Standar","weight_g":118,"minutes":379},{"label":"Multicolor","weight_g":224,"minutes":568}]', '[]'),
(900033, '3d-chameleon-flexi-dragon', 'Chameleon Flexi Dragon', 'Naga-bunglon flexi yang detail dengan ekor melingkar. Print-in-place, tanpa support, seluruh badan lentur.', '3dprint', 'Bunglon dengan ekor menggulung dan tubuh bersegmen yang bisa digoyang. Perpaduan unik antara dua hewan favorit dalam satu model flexi.', '[]', 0, '/produk/3d/batch4/3d-chameleon-flexi-dragon-1.jpg', '["/produk/3d/batch4/3d-chameleon-flexi-dragon-2.jpg"]', true, 66, 211, '[{"label":"Standar","weight_g":66,"minutes":211},{"label":"Multicolor","weight_g":125,"minutes":316}]', '[]'),
(900034, '3d-flexi-playful-star', 'Flexi Playful Star', 'Bintang flexi yang bisa digenggam dan digoyang-goyang. Print-in-place tanpa support, mainan meja yang menyenangkan.', '3dprint', 'Bintang laut versi flexi yang pas digenggam. Gerakannya yang mengalir membuatnya jadi fidget yang seru sekaligus dekorasi lucu.', '[]', 0, '/produk/3d/batch4/3d-flexi-playful-star-1.jpg', '["/produk/3d/batch4/3d-flexi-playful-star-2.jpg"]', true, 126, 403, '[{"label":"Standar","weight_g":126,"minutes":403},{"label":"Multicolor","weight_g":239,"minutes":604}]', '[]'),
(900035, '3d-skeleton-dragon', 'Articulated Skeleton Dragon', 'Naga kerangka artikulasi yang keren dengan tulang belakang bersegmen. Print-in-place, tanpa support.', '3dprint', 'Naga bertulang dengan tubuh yang lentur dan detail rangka yang dramatis. Cocok untuk penggemar fantasi dan koleksi yang menonjol.', '[]', 0, '/produk/3d/batch4/3d-skeleton-dragon-1.jpg', '["/produk/3d/batch4/3d-skeleton-dragon-2.jpg"]', true, 78, 251, '[{"label":"Standar","weight_g":78,"minutes":251},{"label":"Multicolor","weight_g":148,"minutes":376}]', '[]'),
(900036, '3d-infinity-serpent', 'Infinity Serpent Articulated', 'Ular naga panjang artikulasi dengan gerakan mengalir seperti ular sungguhan. Print-in-place, tanpa support.', '3dprint', 'Serpent sangat panjang dengan banyak segmen yang bergerak mengalir. Efek gerakannya menghipnotis dan jadi mainan favorit anak-anak.', '[]', 0, '/produk/3d/batch4/3d-infinity-serpent-1.jpg', '["/produk/3d/batch4/3d-infinity-serpent-2.jpg"]', true, 310, 600, '[{"label":"Standar","weight_g":310,"minutes":600},{"label":"Multicolor","weight_g":589,"minutes":900}]', '[]'),
(900037, '3d-flexi-unicorn-dragon', 'Flexi Unicorn Dragon', 'Naga berunicorn flexi yang cantik dengan sayap dan tanduk. Print-in-place, tanpa support, siap dimainkan.', '3dprint', 'Perpaduan unicorn dan naga dalam bentuk flexi yang lentur. Desainnya yang memukau cocok untuk hadiah dan koleksi fantasi.', '[]', 0, '/produk/3d/batch4/3d-flexi-unicorn-dragon-1.jpg', '["/produk/3d/batch4/3d-flexi-unicorn-dragon-2.jpg"]', true, 17, 55, '[{"label":"Standar","weight_g":17,"minutes":55},{"label":"Multicolor","weight_g":32,"minutes":82}]', '[]');
