-- MakerWorld "Free to Sell" products (@MKONAPELSKY) - free commercial license
-- Run in Supabase SQL Editor.
INSERT INTO products (id, slug, title, description, category, story, materials, total_plastic_kg, image_url, gallery, is_active, weight_g, print_time_min, variants, artists) VALUES
(50, '3d-frog', 'Articulated Frog (Free to Sell)', 'Katak artikulasi fleksibel dengan gerakan meliuk yang memuaskan untuk diputar. Opsi single color hingga tiga warna.', '3dprint', 'Katak artikulasi fleksibel dengan gerakan meliuk yang memuaskan untuk diputar. Opsi single color hingga tiga warna. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/frog-1.jpg', '["/produk/3d/mw/frog-2.jpg","/produk/3d/mw/frog-3.jpeg"]', true, 4, 32, '[{"label":"Single Color 0.12mm, 2 walls, 6%","weight_g":4,"minutes":32},{"label":"Two Colors (eyes) 0.16mm, 2 walls, 6%","weight_g":16,"minutes":75},{"label":"3 Colors eyes bottom 0.16mm, 2 walls, 6%","weight_g":16,"minutes":77},{"label":"Orange Feet 0.12mm, 2 walls, 6%","weight_g":32,"minutes":140}]', '[]'),
(51, '3d-duck', 'Articulated Duck (Free Commercial License)', 'Bebek artikulasi lentur yang lucu dan bisa digoyang. Lisensi komersial gratis dari kreator.', '3dprint', 'Bebek artikulasi lentur yang lucu dan bisa digoyang. Lisensi komersial gratis dari kreator. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/duck-1.jpg', '["/produk/3d/mw/duck-2.jpg","/produk/3d/mw/duck-3.jpg"]', true, 45, 175, '[{"label":"Lower Quality 0.16mm, 2 walls, 8%","weight_g":45,"minutes":175}]', '[]'),
(52, '3d-carrot', 'Happy Carrot (Free Commercial License)', 'Wortel tersenyum berdiri tegak. Hadiah lucu untuk meja dan balkon.', '3dprint', 'Wortel tersenyum berdiri tegak. Hadiah lucu untuk meja dan balkon. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/carrot-1.jpg', '["/produk/3d/mw/carrot-2.jpg","/produk/3d/mw/carrot-3.jpg"]', true, 11, 36, '[{"label":"Single color","weight_g":11,"minutes":36}]', '[]'),
(53, '3d-lizard', 'Flexi Lizard (Free Commercial License)', 'Kadal fleksibel tanpa support. Seru untuk dimainkan dan dipamerkan.', '3dprint', 'Kadal fleksibel tanpa support. Seru untuk dimainkan dan dipamerkan. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/lizard-1.jpg', '["/produk/3d/mw/lizard-2.jpg","/produk/3d/mw/lizard-3.jpg"]', true, 11, 62, '[{"label":"0.08mm layer, 2 walls, 8% infill","weight_g":11,"minutes":62}]', '[]'),
(54, '3d-flexi-christmas-tree', 'Flexi Christmas Tree Ornament (Free to sell)', 'Pohon natal flexi mini yang lentur, cocok untuk dekorasi dan hadiah.', '3dprint', 'Pohon natal flexi mini yang lentur, cocok untuk dekorasi dan hadiah. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/flexi-christmas-tree-1.jpg', '["/produk/3d/mw/flexi-christmas-tree-2.jpg","/produk/3d/mw/flexi-christmas-tree-3.jpg"]', true, 18, 67, '[{"label":"Flexi Ornament","weight_g":18,"minutes":67}]', '[]'),
(55, '3d-mesh-bowl', 'Small Mesh Catch-All Bowl', 'Mangkuk mesh untuk kunci, koin dan aksesoris. Desain transparan yang cantik.', '3dprint', 'Mangkuk mesh untuk kunci, koin dan aksesoris. Desain transparan yang cantik. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/mesh-bowl-1.jpg', '["/produk/3d/mw/mesh-bowl-2.jpg","/produk/3d/mw/mesh-bowl-3.jpg"]', true, 61, 145, '[{"label":"Small catch all","weight_g":61,"minutes":145}]', '[]'),
(56, '3d-tiger-necklace', 'Tiger Hype Necklace', 'Kalung harimau hype bergaya streetwear. Bisa dicetak satu atau dua warna.', '3dprint', 'Kalung harimau hype bergaya streetwear. Bisa dicetak satu atau dua warna. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/tiger-necklace-1.jpg', '["/produk/3d/mw/tiger-necklace-2.jpg","/produk/3d/mw/tiger-necklace-3.jpg"]', true, 64, 116, '[{"label":"0.2mm layer, 2 walls, 5% infill","weight_g":64,"minutes":116}]', '[]'),
(57, '3d-flexi-monster', 'Flexi Monster (No Supports)', 'Monster lucu fleksibel tanpa support. Seru, mudah dicetak.', '3dprint', 'Monster lucu fleksibel tanpa support. Seru, mudah dicetak. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/flexi-monster-1.jpg', '["/produk/3d/mw/flexi-monster-2.jpg","/produk/3d/mw/flexi-monster-3.jpg"]', true, 14, 44, '[{"label":"Single Color - 0.2mm, 2 walls, 12%","weight_g":14,"minutes":44}]', '[]'),
(58, '3d-flexi-unicorn', 'Flexi Unicorn (No Supports)', 'Unicorn fleksibel tanpa support. Cerah, playful, jadi favorit anak.', '3dprint', 'Unicorn fleksibel tanpa support. Cerah, playful, jadi favorit anak. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/flexi-unicorn-1.jpg', '["/produk/3d/mw/flexi-unicorn-2.jpg","/produk/3d/mw/flexi-unicorn-3.jpg"]', true, 8, 35, '[{"label":"0.16mm layer, 2 walls, 12% infill","weight_g":8,"minutes":35}]', '[]'),
(59, '3d-flexi-bear', 'Flexi Bear (No Supports)', 'Beruang fleksibel tanpa support, plus varian gantungan kunci.', '3dprint', 'Beruang fleksibel tanpa support, plus varian gantungan kunci. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/flexi-bear-1.jpg', '["/produk/3d/mw/flexi-bear-2.jpg","/produk/3d/mw/flexi-bear-3.jpg"]', true, 8, 24, '[{"label":"0.2mm layer, 2 walls, 12%","weight_g":8,"minutes":24},{"label":"Keychain Version","weight_g":8,"minutes":34}]', '[]'),
(60, '3d-hex-drip', 'Hex Drip Tray', 'Wadah hex untuk pernak-pernik atau alat tulis kecil.', '3dprint', 'Wadah hex untuk pernak-pernik atau alat tulis kecil. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/hex-drip-1.jpg', '["/produk/3d/mw/hex-drip-2.jpg","/produk/3d/mw/hex-drip-3.jpg"]', true, 46, 77, '[{"label":"0.28mm layer, 2 walls, 8%","weight_g":46,"minutes":77}]', '[]'),
(61, '3d-flexi-worm', 'Flexi Wiggle Worm (Free to sell)', 'Uler flexi yang menggeliat. Pilih single atau multicolor.', '3dprint', 'Uler flexi yang menggeliat. Pilih single atau multicolor. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/flexi-worm-1.jpg', '["/produk/3d/mw/flexi-worm-2.jpg","/produk/3d/mw/flexi-worm-3.jpg"]', true, 49, 149, '[{"label":"Single and Multicolor versions","weight_g":49,"minutes":149}]', '[]'),
(62, '3d-valentine-gear', 'Valentine Gear Fidget', 'Spinner gear fidget - hadiah sayang yang menghipnotis.', '3dprint', 'Spinner gear fidget - hadiah sayang yang menghipnotis. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/valentine-gear-1.jpg', '["/produk/3d/mw/valentine-gear-2.jpg","/produk/3d/mw/valentine-gear-3.jpg"]', true, 29, 104, '[{"label":"0.2mm layer, 2 walls, 10%","weight_g":29,"minutes":104}]', '[]'),
(63, '3d-valentine-cube', 'Valentine Infinity Cube', 'Kubus infinity untuk fidget penghilang penat dengan nuansa valentine.', '3dprint', 'Kubus infinity untuk fidget penghilang penat dengan nuansa valentine. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/valentine-cube-1.jpg', '["/produk/3d/mw/valentine-cube-2.jpg","/produk/3d/mw/valentine-cube-3.jpg"]', true, 43, 106, '[{"label":"Valentine''s Day Infinity Cube","weight_g":43,"minutes":106}]', '[]'),
(64, '3d-spiral-bowl', 'Modern Spiral Catch-All Bowl', 'Mangkuk spiral modern untuk pernak-pernik meja.', '3dprint', 'Mangkuk spiral modern untuk pernak-pernik meja. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/spiral-bowl-1.jpg', '["/produk/3d/mw/spiral-bowl-2.jpg","/produk/3d/mw/spiral-bowl-3.jpg"]', true, 113, 241, '[{"label":"0.2mm layer, 2 walls, 6%","weight_g":113,"minutes":241}]', '[]'),
(65, '3d-mini-dino', 'Mini Articulated Dinosaur', 'Dino mini artikulasi, lucu dan mudah dicetak satu atau dua warna.', '3dprint', 'Dino mini artikulasi, lucu dan mudah dicetak satu atau dua warna. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/mini-dino-1.jpg', '["/produk/3d/mw/mini-dino-2.jpg","/produk/3d/mw/mini-dino-3.jpg"]', true, 34, 125, '[{"label":"Single and Multi-color on separate plates","weight_g":34,"minutes":125}]', '[]'),
(66, '3d-wave-tray', 'Wave Catch-All Tray', 'Nampan dengan lekukan ombak untuk prankan pernik.', '3dprint', 'Nampan dengan lekukan ombak untuk prankan pernik. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/wave-tray-1.jpg', '["/produk/3d/mw/wave-tray-2.jpg","/produk/3d/mw/wave-tray-3.jpg"]', true, 88, 114, '[{"label":"0.2mm layer, 2 walls, 8%","weight_g":88,"minutes":114}]', '[]'),
(67, '3d-spiral-tray', 'Spiral Catch-All Tray', 'Nampan spiral yang anggun untuk meja dan rak.', '3dprint', 'Nampan spiral yang anggun untuk meja dan rak. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/spiral-tray-1.jpg', '["/produk/3d/mw/spiral-tray-2.jpg","/produk/3d/mw/spiral-tray-3.jpg"]', true, 65, 180, '[{"label":"0.2mm layer, 2 walls, 8%","weight_g":65,"minutes":180}]', '[]'),
(68, '3d-daisy-magnets', 'Daisy Magnets', 'Set magnet bunga daisy berwarna-warni untuk kulkas dan papan.', '3dprint', 'Set magnet bunga daisy berwarna-warni untuk kulkas dan papan. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/daisy-magnets-1.jpg', '["/produk/3d/mw/daisy-magnets-2.jpg","/produk/3d/mw/daisy-magnets-3.jpg"]', true, 20, 50, '[{"label":"small and large on separate plates","weight_g":20,"minutes":50}]', '[]'),
(69, '3d-flexi-fox', 'Flexi Flying Fox (Free to Sell)', 'Kelelawar rubah terbang yang lentuk. Sensasional di udara.', '3dprint', 'Kelelawar rubah terbang yang lentuk. Sensasional di udara. Model free-to-sell dengan lisensi komersial bebas dari kreator.', '[]', 0, '/produk/3d/mw/flexi-fox-1.jpg', '["/produk/3d/mw/flexi-fox-2.jpeg","/produk/3d/mw/flexi-fox-3.jpeg"]', true, 7, 42, '[{"label":"0.16mm layer, 3 walls, 6%","weight_g":7,"minutes":42}]', '[]');
